/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import ModCaja.ReImpresionDocVenta;
import ModCaja.RegistroCobroClientes1;
import ModCaja.TurnoVentas;
import ModCaja.Ventas;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.net.URL;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import utiles.DBManager;
import utiles.InfoErrores;

/**
 *
 * @author Andres
 */
public class CajaMain extends javax.swing.JFrame {

    public static boolean resultExitVentas = false; 
    public static boolean resultExitReImpresiones = false; 
    public static boolean resultExitCobroCuentas = false; 
    public static boolean resultExitTurnos = false; 
    
    Ventas ventas = null;
    RegistroCobroClientes1 cobroClientes = null;
    
    public CajaMain() {
        initComponents();
        cerrarVentana();
        labelBotones();
    }

    private void msgDesarrollo(){
        JOptionPane.showMessageDialog(this, "Módulo en desarrollo!", "ATENCION", JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void salir(){
        //int exit = JOptionPane.showConfirmDialog(this, "Desea salir del sistema?", "Salir del sistema", JOptionPane.YES_NO_OPTION);
        //if(exit == 0){
            FormMain.resultExitCajaMain = false;
            this.dispose();
        //}
    }
    
    private boolean controlForms(){
        boolean result = true;
        if(resultExitVentas == false && resultExitReImpresiones == false && resultExitCobroCuentas == false && resultExitTurnos == false){
            result = false;
        }
        return result;
    }
    
    private void labelBotones(){
        jBReImpresionDocs.setLabel("<html><p align = " + "center" + ">Consulta<br>Re Impresión</br><br>Docs</br></p></html>");
        jBTurnoVenta.setLabel("<html><p align = " + "center" + ">Turno<br>de</br><br>Ventas</br></p></html>");
        jBVentas.setLabel("<html><p align = " + "center" + ">Registro<br>de</br><br>Ventas</br></p></html>");
        jBCobroClientes.setLabel("<html><p align = " + "center" + ">Cobro<br>de</br><br>Cuentas</br></p></html>");
    }
    
    private void cerrarVentana()
    {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e)
            {
                if(controlForms()){
                    JOptionPane.showMessageDialog(CajaMain.this, "Existen ventanas abiertas" , "ATENCION", JOptionPane.WARNING_MESSAGE);
                }else{
                    salir();
                }
            }
        });
    }
    
    private boolean existeTurnoHabilitado(){
        boolean result = false;
        try{
            String sql = "SELECT nro_turno FROM turno WHERE cod_caja = " + FormMain.codCaja + " AND fec_cierre_turno IS null";
            ResultSet rs = DBManager.ejecutarDSL(sql);
            if(rs != null){
                if(rs.next()){
                    result = true;
                }
            }
        }catch(Exception ex){
            ex.printStackTrace();
            InfoErrores.errores(ex);
        }finally{
            DBManager.CerrarStatements();
        }
        return result;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBTurnoVenta = new javax.swing.JButton();
        jBReImpresionDocs = new javax.swing.JButton();
        jBVentas = new javax.swing.JButton();
        jBCobroClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ATOMSystems|Main - Módulo de Ventas");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jBTurnoVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBTurnoVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/agregar24.png"))); // NOI18N
        jBTurnoVenta.setText("Turnos");
        jBTurnoVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTurnoVentaActionPerformed(evt);
            }
        });

        jBReImpresionDocs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBReImpresionDocs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imprimir24.png"))); // NOI18N
        jBReImpresionDocs.setText("Re Impresion docs");
        jBReImpresionDocs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBReImpresionDocsActionPerformed(evt);
            }
        });

        jBVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/venta24.png"))); // NOI18N
        jBVentas.setText("Ventas");
        jBVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVentasActionPerformed(evt);
            }
        });

        jBCobroClientes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBCobroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/registro_compra24.png"))); // NOI18N
        jBCobroClientes.setText("Cobro Cuentas");
        jBCobroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCobroClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBTurnoVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCobroClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBReImpresionDocs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBCobroClientes, jBReImpresionDocs, jBTurnoVenta, jBVentas});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTurnoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBReImpresionDocs)
                    .addComponent(jBVentas)
                    .addComponent(jBCobroClientes))
                .addContainerGap(385, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBCobroClientes, jBReImpresionDocs, jBTurnoVenta, jBVentas});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(630, 483));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVentasActionPerformed
        salir();
        if(existeTurnoHabilitado()){
            if (ventas == null){
            ventas= new Ventas();
            ventas.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ventas.setVisible(true);
            resultExitVentas = true;
            }else{
                ventas.setState(Frame.NORMAL);
                ventas.setVisible(true);
                resultExitVentas = true;
            }
        }else{
            JOptionPane.showMessageDialog(this, "No existe turno habilitado!", "ATENCION", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBVentasActionPerformed

    private void jBTurnoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTurnoVentaActionPerformed
        salir();
        TurnoVentas turno = new TurnoVentas(new JFrame(), true);
        turno.pack();
        turno.setVisible(true);        
    }//GEN-LAST:event_jBTurnoVentaActionPerformed

    private void jBReImpresionDocsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBReImpresionDocsActionPerformed
        ReImpresionDocVenta impresion = new ReImpresionDocVenta(new JFrame(), true);
        impresion.pack();
        impresion.setVisible(true);
        //msgDesarrollo();
    }//GEN-LAST:event_jBReImpresionDocsActionPerformed

    private void jBCobroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCobroClientesActionPerformed
        salir();
        if(existeTurnoHabilitado()){
            cobroClientes= new RegistroCobroClientes1(new JFrame(), true, "COBRANZAS", "");
            cobroClientes.pack();
            cobroClientes.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "No existe turno habilitado!", "ATENCION", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBCobroClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CajaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CajaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CajaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CajaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CajaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCobroClientes;
    private javax.swing.JButton jBReImpresionDocs;
    private javax.swing.JButton jBTurnoVenta;
    private javax.swing.JButton jBVentas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
