/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import ModFinanciero.ModificarVencimientos;
import ModFinanciero.ReDefinicionCuotas;
import ModFinanciero.informes.CuentasClientes;
import ModFinanciero.informes.InfCobranzasClientes;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author Andres
 */
public class FormFinanciero extends javax.swing.JFrame {

    /**
     * Creates new form FormFinanciero
     */
    public FormFinanciero() {
        initComponents();
        cerrarVentana();
    }

    private void cerrarVentana()
    {
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e)
            {
                FormMain.resultExitFinanciero = false;
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuOperaciones = new javax.swing.JMenu();
        jMnuIModificarVencimiento = new javax.swing.JMenuItem();
        jMnuIRedefinicionCuotas = new javax.swing.JMenuItem();
        jMnuMantenimiento = new javax.swing.JMenu();
        jMnuInformes = new javax.swing.JMenu();
        jMnuICobroClientes = new javax.swing.JMenuItem();
        jMnuICuentasClientes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ATOMSystems|Main - Módulo Financiero");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1264, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );

        jMnuOperaciones.setText("Operaciones");
        jMnuOperaciones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMnuIModificarVencimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIModificarVencimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/calculo_dias_horas24.png"))); // NOI18N
        jMnuIModificarVencimiento.setText("Modificar Vencimientos de Cuotas");
        jMnuIModificarVencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIModificarVencimientoActionPerformed(evt);
            }
        });
        jMnuOperaciones.add(jMnuIModificarVencimiento);

        jMnuIRedefinicionCuotas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIRedefinicionCuotas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/modificar24.png"))); // NOI18N
        jMnuIRedefinicionCuotas.setText("Re definición de cuotas");
        jMnuIRedefinicionCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIRedefinicionCuotasActionPerformed(evt);
            }
        });
        jMnuOperaciones.add(jMnuIRedefinicionCuotas);

        jMenuBar1.add(jMnuOperaciones);

        jMnuMantenimiento.setText("Mantenimiento");
        jMnuMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMnuMantenimiento);

        jMnuInformes.setText("Informes");
        jMnuInformes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMnuICobroClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuICobroClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/diashoras24.png"))); // NOI18N
        jMnuICobroClientes.setText("Cobro de Clientes");
        jMnuICobroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuICobroClientesActionPerformed(evt);
            }
        });
        jMnuInformes.add(jMnuICobroClientes);

        jMnuICuentasClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuICuentasClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cuenta_cliente24.png"))); // NOI18N
        jMnuICuentasClientes.setText("Cuentas de Clientes");
        jMnuICuentasClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuICuentasClientesActionPerformed(evt);
            }
        });
        jMnuInformes.add(jMnuICuentasClientes);

        jMenuBar1.add(jMnuInformes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1264, 761));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuICobroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuICobroClientesActionPerformed
        InfCobranzasClientes cobros = new InfCobranzasClientes(new JFrame(), true);
        cobros.pack();
        cobros.setVisible(true);
    }//GEN-LAST:event_jMnuICobroClientesActionPerformed

    private void jMnuIModificarVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIModificarVencimientoActionPerformed
        ModificarVencimientos mod = new ModificarVencimientos(new JFrame(), true);
        mod.pack();
        mod.setVisible(true);
    }//GEN-LAST:event_jMnuIModificarVencimientoActionPerformed

    private void jMnuIRedefinicionCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIRedefinicionCuotasActionPerformed
        ReDefinicionCuotas redefinicion = new ReDefinicionCuotas(new JFrame(), true);
        redefinicion.pack();
        redefinicion.setVisible(true);
    }//GEN-LAST:event_jMnuIRedefinicionCuotasActionPerformed

    private void jMnuICuentasClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuICuentasClientesActionPerformed
        CuentasClientes cuentas = new CuentasClientes(new JFrame(), true);
        cuentas.pack();
        cuentas.setVisible(true);
    }//GEN-LAST:event_jMnuICuentasClientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormFinanciero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormFinanciero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormFinanciero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormFinanciero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormFinanciero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnuICobroClientes;
    private javax.swing.JMenuItem jMnuICuentasClientes;
    private javax.swing.JMenuItem jMnuIModificarVencimiento;
    private javax.swing.JMenuItem jMnuIRedefinicionCuotas;
    private javax.swing.JMenu jMnuInformes;
    private javax.swing.JMenu jMnuMantenimiento;
    private javax.swing.JMenu jMnuOperaciones;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
