/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import javax.swing.JFrame;
import ModRegistros.Articulos;
import ModRegistros.Barrios;
import ModRegistros.Ciudades;
import ModRegistros.Clientes;
import ModRegistros.Grupos;
import ModRegistros.Marcas;
import ModRegistros.Monedas;
import ModRegistros.Parametros;
import ModRegistros.Proveedores;
import ModRegistros.Usuarios;
import ModRegistros.informes.InformeVentas;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;

/**
 *
 * @author Andres
 */
public class FormRegistrosBase extends javax.swing.JFrame {

    /**
     * Creates new form FormRegistrosBase
     */
    public FormRegistrosBase() {
        initComponents();
        cerrarVentana();
    }

    private void cerrarVentana()
    {
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e)
            {
                FormMain.resultExitRegistros = false;
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuRegistros = new javax.swing.JMenu();
        jMnuArticulos = new javax.swing.JMenuItem();
        jMnuGruposSub = new javax.swing.JMenuItem();
        jMnuMarcas = new javax.swing.JMenuItem();
        jMnuCiudades = new javax.swing.JMenuItem();
        jMnuBarrios = new javax.swing.JMenuItem();
        jMnuProveedores = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMnuIClientes = new javax.swing.JMenuItem();
        jMnuSistema = new javax.swing.JMenu();
        jMnuUsuarios = new javax.swing.JMenuItem();
        jMnuParametros = new javax.swing.JMenuItem();
        jMnuInformes = new javax.swing.JMenu();
        jMnuIInformVentas = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ATOMSystems|Main - Módulo de Registros Base");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1264, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );

        jMnuRegistros.setText("Registros");
        jMnuRegistros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMnuArticulos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/abastecimiento24.png"))); // NOI18N
        jMnuArticulos.setText("Artículos");
        jMnuArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuArticulosActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuArticulos);

        jMnuGruposSub.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuGruposSub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/grupos24.png"))); // NOI18N
        jMnuGruposSub.setText("Grupos");
        jMnuGruposSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuGruposSubActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuGruposSub);

        jMnuMarcas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/marcas24.png"))); // NOI18N
        jMnuMarcas.setText("Marcas");
        jMnuMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuMarcasActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuMarcas);

        jMnuCiudades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuCiudades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ciudades24.png"))); // NOI18N
        jMnuCiudades.setText("Ciudades");
        jMnuCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuCiudadesActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuCiudades);

        jMnuBarrios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuBarrios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/barrios24.png"))); // NOI18N
        jMnuBarrios.setText("Barrios");
        jMnuBarrios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuBarriosActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuBarrios);

        jMnuProveedores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/proveedores24.png"))); // NOI18N
        jMnuProveedores.setText("Proveedores");
        jMnuProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProveedoresActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuProveedores);

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/moneda24.png"))); // NOI18N
        jMenuItem1.setText("Monedas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMenuItem1);

        jMnuIClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cliente24.png"))); // NOI18N
        jMnuIClientes.setText("Clientes");
        jMnuIClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIClientesActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuIClientes);

        jMenuBar1.add(jMnuRegistros);

        jMnuSistema.setText("Sistema");
        jMnuSistema.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMnuUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/usuarios24.png"))); // NOI18N
        jMnuUsuarios.setText("Usuarios del sistema");
        jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuariosActionPerformed(evt);
            }
        });
        jMnuSistema.add(jMnuUsuarios);

        jMnuParametros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/parametros24.png"))); // NOI18N
        jMnuParametros.setText("Parámetros del sistema");
        jMnuParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuParametrosActionPerformed(evt);
            }
        });
        jMnuSistema.add(jMnuParametros);

        jMenuBar1.add(jMnuSistema);

        jMnuInformes.setText("Informes ");
        jMnuInformes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMnuIInformVentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIInformVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/informe_ventas24.png"))); // NOI18N
        jMnuIInformVentas.setText("Ventas");
        jMnuIInformVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIInformVentasActionPerformed(evt);
            }
        });
        jMnuInformes.add(jMnuIInformVentas);

        jMenuBar1.add(jMnuInformes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1264, 761));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuArticulosActionPerformed
        Articulos.callFromArticulo = true;
        Articulos articulos = new Articulos(new JFrame(), true, "", "");
        articulos.pack();
        articulos.setVisible(true);
    }//GEN-LAST:event_jMnuArticulosActionPerformed

    private void jMnuGruposSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuGruposSubActionPerformed
        Articulos.callFromArticulo = false;
        Grupos grupo = new Grupos(new JFrame(), true);
        grupo.pack();
        grupo.setVisible(true);
    }//GEN-LAST:event_jMnuGruposSubActionPerformed

    private void jMnuMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuMarcasActionPerformed
        Marcas marcas = new Marcas(new JFrame(), true);
        marcas.pack();
        marcas.setVisible(true);
    }//GEN-LAST:event_jMnuMarcasActionPerformed

    private void jMnuCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuCiudadesActionPerformed
        Ciudades ciudades = new Ciudades(new JFrame(), true);
        ciudades.pack();
        ciudades.setVisible(true);
    }//GEN-LAST:event_jMnuCiudadesActionPerformed

    private void jMnuBarriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuBarriosActionPerformed
        Barrios barrios = new Barrios(new JFrame(), true);
        barrios.pack();
        barrios.setVisible(true);
    }//GEN-LAST:event_jMnuBarriosActionPerformed

    private void jMnuProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProveedoresActionPerformed
        Proveedores proveedores = new Proveedores(new JFrame(), true);
        proveedores.pack();
        proveedores.setVisible(true);
    }//GEN-LAST:event_jMnuProveedoresActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Monedas monedas = new Monedas(new JFrame(), true);
        monedas.pack();
        monedas.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuariosActionPerformed
        Usuarios usuarios = new Usuarios(new JFrame(), true);
        usuarios.pack();
        usuarios.setVisible(true);
    }//GEN-LAST:event_jMnuUsuariosActionPerformed

    private void jMnuIClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIClientesActionPerformed
        Clientes clientes = new Clientes(new JFrame(), true);
        clientes.pack();
        clientes.setVisible(true);
    }//GEN-LAST:event_jMnuIClientesActionPerformed

    private void jMnuIInformVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIInformVentasActionPerformed
        InformeVentas informeVtas = new InformeVentas(new JFrame(), true);
        informeVtas.pack();
        informeVtas.setVisible(true);
    }//GEN-LAST:event_jMnuIInformVentasActionPerformed

    private void jMnuParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuParametrosActionPerformed
        Parametros params = new Parametros(new JFrame(), true);
        params.pack();
        params.setVisible(true);
    }//GEN-LAST:event_jMnuParametrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistrosBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistrosBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistrosBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistrosBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegistrosBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMnuArticulos;
    private javax.swing.JMenuItem jMnuBarrios;
    private javax.swing.JMenuItem jMnuCiudades;
    private javax.swing.JMenuItem jMnuGruposSub;
    private javax.swing.JMenuItem jMnuIClientes;
    private javax.swing.JMenuItem jMnuIInformVentas;
    private javax.swing.JMenu jMnuInformes;
    private javax.swing.JMenuItem jMnuMarcas;
    private javax.swing.JMenuItem jMnuParametros;
    private javax.swing.JMenuItem jMnuProveedores;
    private javax.swing.JMenu jMnuRegistros;
    private javax.swing.JMenu jMnuSistema;
    private javax.swing.JMenuItem jMnuUsuarios;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
