/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import javax.swing.JFrame;
import ModRegistros.Articulos;
import ModRegistros.Barrios;
import ModRegistros.Ciudades;
import ModRegistros.Clientes;
import ModRegistros.Grupos;
import ModRegistros.Marcas;
import ModRegistros.Monedas;
import ModRegistros.Parametros;
import ModRegistros.Proveedores;
import ModRegistros.Usuarios1;
import ModRegistros.informes.InformeGralVentas;
import ModRegistros.informes.InformeVentas;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import utiles.ClassMenu;

/**
 *
 * @author Andres
 */
public class FormRegistrosBase extends javax.swing.JFrame {

    ClassMenu classMenu = new ClassMenu();
    
    public FormRegistrosBase(String user, String grupo) {
        initComponents();
        cerrarVentana();
        jMnuBarRegistros.setVisible(false);
        classMenu.permisosMenu(user, grupo, jMnuBarRegistros);
    }

    private void cerrarVentana()
    {
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e)
            {
                FormMain.resultExitRegistros = false;
                FormMain.formRegBase = null;
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jMnuBarRegistros = new javax.swing.JMenuBar();
        jMnuRegistros = new javax.swing.JMenu();
        jMnuIArticulos = new javax.swing.JMenuItem();
        jMnuIGruposSub = new javax.swing.JMenuItem();
        jMnuIMarcas = new javax.swing.JMenuItem();
        jMnuICiudades = new javax.swing.JMenuItem();
        jMnuIBarrios = new javax.swing.JMenuItem();
        jMnuIProveedores = new javax.swing.JMenuItem();
        jMnuIMonedas = new javax.swing.JMenuItem();
        jMnuIClientes = new javax.swing.JMenuItem();
        jMnuSistema = new javax.swing.JMenu();
        jMnuIUsuarios = new javax.swing.JMenuItem();
        jMnuIParametros = new javax.swing.JMenuItem();
        jMnuInformesRegistrosBase = new javax.swing.JMenu();
        jMnuVentas = new javax.swing.JMenu();
        jMnuIInformVentas = new javax.swing.JMenuItem();
        jMnuIInformeGralVentas = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ATOMSystems|Main - Módulo de Registros Base");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1264, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 739, Short.MAX_VALUE)
        );

        jMnuBarRegistros.setName("jMnuBarRegistros"); // NOI18N

        jMnuRegistros.setText("Registros");
        jMnuRegistros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuRegistros.setName("jMnuRegistros"); // NOI18N

        jMnuIArticulos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/abastecimiento24.png"))); // NOI18N
        jMnuIArticulos.setText("Artículos");
        jMnuIArticulos.setName("jMnuIArticulos"); // NOI18N
        jMnuIArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIArticulosActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuIArticulos);

        jMnuIGruposSub.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIGruposSub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/grupos24.png"))); // NOI18N
        jMnuIGruposSub.setText("Grupos");
        jMnuIGruposSub.setName("jMnuIGruposSub"); // NOI18N
        jMnuIGruposSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIGruposSubActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuIGruposSub);

        jMnuIMarcas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/marcas24.png"))); // NOI18N
        jMnuIMarcas.setText("Marcas");
        jMnuIMarcas.setName("jMnuIMarcas"); // NOI18N
        jMnuIMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIMarcasActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuIMarcas);

        jMnuICiudades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuICiudades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ciudades24.png"))); // NOI18N
        jMnuICiudades.setText("Ciudades");
        jMnuICiudades.setName("jMnuICiudades"); // NOI18N
        jMnuICiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuICiudadesActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuICiudades);

        jMnuIBarrios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIBarrios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/barrios24.png"))); // NOI18N
        jMnuIBarrios.setText("Barrios");
        jMnuIBarrios.setName("jMnuIBarrios"); // NOI18N
        jMnuIBarrios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIBarriosActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuIBarrios);

        jMnuIProveedores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/proveedores24.png"))); // NOI18N
        jMnuIProveedores.setText("Proveedores");
        jMnuIProveedores.setName("jMnuIProveedores"); // NOI18N
        jMnuIProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIProveedoresActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuIProveedores);

        jMnuIMonedas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIMonedas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/moneda24.png"))); // NOI18N
        jMnuIMonedas.setText("Monedas");
        jMnuIMonedas.setName("jMnuIMonedas"); // NOI18N
        jMnuIMonedas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIMonedasActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuIMonedas);

        jMnuIClientes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cliente24.png"))); // NOI18N
        jMnuIClientes.setText("Clientes");
        jMnuIClientes.setName("jMnuIClientes"); // NOI18N
        jMnuIClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIClientesActionPerformed(evt);
            }
        });
        jMnuRegistros.add(jMnuIClientes);

        jMnuBarRegistros.add(jMnuRegistros);

        jMnuSistema.setText("Sistema");
        jMnuSistema.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuSistema.setName("jMnuSistema"); // NOI18N

        jMnuIUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/usuarios24.png"))); // NOI18N
        jMnuIUsuarios.setText("Usuarios del sistema");
        jMnuIUsuarios.setName("jMnuIUsuarios"); // NOI18N
        jMnuIUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIUsuariosActionPerformed(evt);
            }
        });
        jMnuSistema.add(jMnuIUsuarios);

        jMnuIParametros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/parametros24.png"))); // NOI18N
        jMnuIParametros.setText("Parámetros del sistema");
        jMnuIParametros.setName("jMnuIParametros"); // NOI18N
        jMnuIParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIParametrosActionPerformed(evt);
            }
        });
        jMnuSistema.add(jMnuIParametros);

        jMnuBarRegistros.add(jMnuSistema);

        jMnuInformesRegistrosBase.setText("Informes ");
        jMnuInformesRegistrosBase.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuInformesRegistrosBase.setName("jMnuInformesRegistrosBase"); // NOI18N

        jMnuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/barChart20.png"))); // NOI18N
        jMnuVentas.setText("Ventas");
        jMnuVentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuVentas.setName("jMnuVentas"); // NOI18N

        jMnuIInformVentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIInformVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/informe_ventas24.png"))); // NOI18N
        jMnuIInformVentas.setText("Ventas");
        jMnuIInformVentas.setName("jMnuIInformVentas"); // NOI18N
        jMnuIInformVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIInformVentasActionPerformed(evt);
            }
        });
        jMnuVentas.add(jMnuIInformVentas);

        jMnuIInformeGralVentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIInformeGralVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/consulta_movimiento24.png"))); // NOI18N
        jMnuIInformeGralVentas.setText("Informe Gral de Ventas");
        jMnuIInformeGralVentas.setName("jMnuIInformeGralVentas"); // NOI18N
        jMnuIInformeGralVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIInformeGralVentasActionPerformed(evt);
            }
        });
        jMnuVentas.add(jMnuIInformeGralVentas);

        jMnuInformesRegistrosBase.add(jMnuVentas);

        jMnuBarRegistros.add(jMnuInformesRegistrosBase);

        setJMenuBar(jMnuBarRegistros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1264, 761));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuIArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIArticulosActionPerformed
        Articulos.callFromArticulo = true;
        Articulos articulos = new Articulos(new JFrame(), true, "", "");
        articulos.pack();
        articulos.setVisible(true);
    }//GEN-LAST:event_jMnuIArticulosActionPerformed

    private void jMnuIGruposSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIGruposSubActionPerformed
        Articulos.callFromArticulo = false;
        Grupos grupo = new Grupos(new JFrame(), true);
        grupo.pack();
        grupo.setVisible(true);
    }//GEN-LAST:event_jMnuIGruposSubActionPerformed

    private void jMnuIMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIMarcasActionPerformed
        Marcas marcas = new Marcas(new JFrame(), true);
        marcas.pack();
        marcas.setVisible(true);
    }//GEN-LAST:event_jMnuIMarcasActionPerformed

    private void jMnuICiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuICiudadesActionPerformed
        Ciudades ciudades = new Ciudades(new JFrame(), true);
        ciudades.pack();
        ciudades.setVisible(true);
    }//GEN-LAST:event_jMnuICiudadesActionPerformed

    private void jMnuIBarriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIBarriosActionPerformed
        Barrios barrios = new Barrios(new JFrame(), true);
        barrios.pack();
        barrios.setVisible(true);
    }//GEN-LAST:event_jMnuIBarriosActionPerformed

    private void jMnuIProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIProveedoresActionPerformed
        Proveedores proveedores = new Proveedores(new JFrame(), true);
        proveedores.pack();
        proveedores.setVisible(true);
    }//GEN-LAST:event_jMnuIProveedoresActionPerformed

    private void jMnuIMonedasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIMonedasActionPerformed
        Monedas monedas = new Monedas(new JFrame(), true);
        monedas.pack();
        monedas.setVisible(true);
    }//GEN-LAST:event_jMnuIMonedasActionPerformed

    private void jMnuIUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIUsuariosActionPerformed
        Usuarios1 usuarios = new Usuarios1(new JFrame(), true);
        usuarios.pack();
        usuarios.setVisible(true);
    }//GEN-LAST:event_jMnuIUsuariosActionPerformed

    private void jMnuIClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIClientesActionPerformed
        Clientes clientes = new Clientes(new JFrame(), true);
        clientes.pack();
        clientes.setVisible(true);
    }//GEN-LAST:event_jMnuIClientesActionPerformed

    private void jMnuIParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIParametrosActionPerformed
        Parametros params = new Parametros(new JFrame(), true);
        params.pack();
        params.setVisible(true);
    }//GEN-LAST:event_jMnuIParametrosActionPerformed

    private void jMnuIInformVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIInformVentasActionPerformed
        InformeVentas informeVtas = new InformeVentas(new JFrame(), true);
        informeVtas.pack();
        informeVtas.setVisible(true);
    }//GEN-LAST:event_jMnuIInformVentasActionPerformed

    private void jMnuIInformeGralVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIInformeGralVentasActionPerformed
        JOptionPane.showMessageDialog(this, "MÓDULO EN DESARROLLO!\nLos reportes aun no cuentan con detalles!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        InformeGralVentas gral = new InformeGralVentas(new JFrame(), true);
        gral.pack();
        gral.setVisible(true);
    }//GEN-LAST:event_jMnuIInformeGralVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegistrosBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegistrosBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegistrosBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegistrosBase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FormRegistrosBase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMnuBarRegistros;
    private javax.swing.JMenuItem jMnuIArticulos;
    private javax.swing.JMenuItem jMnuIBarrios;
    private javax.swing.JMenuItem jMnuICiudades;
    private javax.swing.JMenuItem jMnuIClientes;
    private javax.swing.JMenuItem jMnuIGruposSub;
    private javax.swing.JMenuItem jMnuIInformVentas;
    private javax.swing.JMenuItem jMnuIInformeGralVentas;
    private javax.swing.JMenuItem jMnuIMarcas;
    private javax.swing.JMenuItem jMnuIMonedas;
    private javax.swing.JMenuItem jMnuIParametros;
    private javax.swing.JMenuItem jMnuIProveedores;
    private javax.swing.JMenuItem jMnuIUsuarios;
    private javax.swing.JMenu jMnuInformesRegistrosBase;
    private javax.swing.JMenu jMnuRegistros;
    private javax.swing.JMenu jMnuSistema;
    private javax.swing.JMenu jMnuVentas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
