/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import ModAbastecimiento.AjusteStock;
import ModAbastecimiento.AnulacionDocCompraGasto;
import ModAbastecimiento.RecepcionDirectaMercaderias;
import ModAbastecimiento.RegistroCompraMercaderias;
import ModAbastecimiento.RegistroComprobanteGastos;
import ModAbastecimiento.informes.InformeArticulos;
import ModAbastecimiento.informes.InformeComprasGastos;
import ModAbastecimiento.informes.InformeReImpresionAjusteStock;
import ModAbastecimiento.informes.InformeReImpresionRecepcionMercaderia;
import ModRegistros.Articulos;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JFrame;
import utiles.ClassMenu;

/**
 *
 * @author Andres
 */
public class FormAbastecimiento extends javax.swing.JFrame {

    ClassMenu classMenu = new ClassMenu();
    
    public FormAbastecimiento(String user, String grupo) {
        initComponents();
        cerrarVentana();
        jMenuBar1.setVisible(false);
        classMenu.permisosMenu(user, grupo, jMenuBar1);
    }
    
    private void cerrarVentana()
    {
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e)
            {
                FormMain.resultExitAbastecimiento = false;
                FormMain.formAbast = null;
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuOperacionesAbastecimiento = new javax.swing.JMenu();
        jMnuIRecepcionMercaderias = new javax.swing.JMenuItem();
        jMnuIRegistroCompraMercaderias = new javax.swing.JMenuItem();
        jMnuIRegistroComprobantesGastos = new javax.swing.JMenuItem();
        jMnuIAnulacionDocCompra = new javax.swing.JMenuItem();
        jMnuStock = new javax.swing.JMenu();
        jMnuIAjusteStock = new javax.swing.JMenuItem();
        jMnuConsultas = new javax.swing.JMenu();
        jMnuIArticulosConsulta = new javax.swing.JMenuItem();
        jMnuInformesAbastecimiento = new javax.swing.JMenu();
        jMnuIReImpresionRecepcion = new javax.swing.JMenuItem();
        jMnuIReImpresionAjuste = new javax.swing.JMenuItem();
        jMnuIComprasGastos = new javax.swing.JMenuItem();
        jMnuIListadoArticulos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ATOMSystems|Main - Módulo de Abastecimiento");
        setPreferredSize(new java.awt.Dimension(1264, 761));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1264, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMnuOperacionesAbastecimiento.setText("Operaciones");
        jMnuOperacionesAbastecimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuOperacionesAbastecimiento.setName("jMnuOperacionesAbastecimiento"); // NOI18N

        jMnuIRecepcionMercaderias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIRecepcionMercaderias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/recepcion_mercaderias24.png"))); // NOI18N
        jMnuIRecepcionMercaderias.setText("Recepción de Mercaderías");
        jMnuIRecepcionMercaderias.setName("jMnuIRecepcionMercaderias"); // NOI18N
        jMnuIRecepcionMercaderias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIRecepcionMercaderiasActionPerformed(evt);
            }
        });
        jMnuOperacionesAbastecimiento.add(jMnuIRecepcionMercaderias);

        jMnuIRegistroCompraMercaderias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIRegistroCompraMercaderias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/registro_compra24.png"))); // NOI18N
        jMnuIRegistroCompraMercaderias.setText("Registro de Compra de Mercaderías");
        jMnuIRegistroCompraMercaderias.setName("jMnuIRegistroCompraMercaderias"); // NOI18N
        jMnuIRegistroCompraMercaderias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIRegistroCompraMercaderiasActionPerformed(evt);
            }
        });
        jMnuOperacionesAbastecimiento.add(jMnuIRegistroCompraMercaderias);

        jMnuIRegistroComprobantesGastos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIRegistroComprobantesGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gastos24.png"))); // NOI18N
        jMnuIRegistroComprobantesGastos.setText("Registro de Comprobantes de Gastos");
        jMnuIRegistroComprobantesGastos.setName("jMnuIRegistroComprobantesGastos"); // NOI18N
        jMnuIRegistroComprobantesGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIRegistroComprobantesGastosActionPerformed(evt);
            }
        });
        jMnuOperacionesAbastecimiento.add(jMnuIRegistroComprobantesGastos);

        jMnuIAnulacionDocCompra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIAnulacionDocCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/eliminar24.png"))); // NOI18N
        jMnuIAnulacionDocCompra.setText("Anulación de doc de compras/gastos");
        jMnuIAnulacionDocCompra.setName("jMnuIAnulacionDocCompra"); // NOI18N
        jMnuIAnulacionDocCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIAnulacionDocCompraActionPerformed(evt);
            }
        });
        jMnuOperacionesAbastecimiento.add(jMnuIAnulacionDocCompra);

        jMenuBar1.add(jMnuOperacionesAbastecimiento);

        jMnuStock.setText("Stock");
        jMnuStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuStock.setName("jMnuStock"); // NOI18N

        jMnuIAjusteStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIAjusteStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ajuste_stock24.png"))); // NOI18N
        jMnuIAjusteStock.setText("Ajuste de Stock");
        jMnuIAjusteStock.setName("jMnuIAjusteStock"); // NOI18N
        jMnuIAjusteStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIAjusteStockActionPerformed(evt);
            }
        });
        jMnuStock.add(jMnuIAjusteStock);

        jMenuBar1.add(jMnuStock);

        jMnuConsultas.setText("Consultas");
        jMnuConsultas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuConsultas.setName("jMnuConsultas"); // NOI18N

        jMnuIArticulosConsulta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIArticulosConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/abastecimiento24.png"))); // NOI18N
        jMnuIArticulosConsulta.setText("Articulos");
        jMnuIArticulosConsulta.setName("jMnuIArticulosConsulta"); // NOI18N
        jMnuIArticulosConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIArticulosConsultaActionPerformed(evt);
            }
        });
        jMnuConsultas.add(jMnuIArticulosConsulta);

        jMenuBar1.add(jMnuConsultas);

        jMnuInformesAbastecimiento.setText("Informes ");
        jMnuInformesAbastecimiento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuInformesAbastecimiento.setName("jMnuInformesAbastecimiento"); // NOI18N

        jMnuIReImpresionRecepcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIReImpresionRecepcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/recepcion_mercaderias24.png"))); // NOI18N
        jMnuIReImpresionRecepcion.setText("Re Impresión Recepción de Mercaderias");
        jMnuIReImpresionRecepcion.setName("jMnuIReImpresionRecepcion"); // NOI18N
        jMnuIReImpresionRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIReImpresionRecepcionActionPerformed(evt);
            }
        });
        jMnuInformesAbastecimiento.add(jMnuIReImpresionRecepcion);

        jMnuIReImpresionAjuste.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIReImpresionAjuste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ajuste_stock24.png"))); // NOI18N
        jMnuIReImpresionAjuste.setText("Re Impresión de Ajuste de Stock");
        jMnuIReImpresionAjuste.setName("jMnuIReImpresionAjuste"); // NOI18N
        jMnuIReImpresionAjuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIReImpresionAjusteActionPerformed(evt);
            }
        });
        jMnuInformesAbastecimiento.add(jMnuIReImpresionAjuste);

        jMnuIComprasGastos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIComprasGastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/inf_comprasgastos24.png"))); // NOI18N
        jMnuIComprasGastos.setText("Compras y Gastos");
        jMnuIComprasGastos.setName("jMnuIComprasGastos"); // NOI18N
        jMnuIComprasGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIComprasGastosActionPerformed(evt);
            }
        });
        jMnuInformesAbastecimiento.add(jMnuIComprasGastos);

        jMnuIListadoArticulos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMnuIListadoArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/listado_articulos24.png"))); // NOI18N
        jMnuIListadoArticulos.setText("Listado de Artículos");
        jMnuIListadoArticulos.setName("jMnuIListadoArticulos"); // NOI18N
        jMnuIListadoArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuIListadoArticulosActionPerformed(evt);
            }
        });
        jMnuInformesAbastecimiento.add(jMnuIListadoArticulos);

        jMenuBar1.add(jMnuInformesAbastecimiento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1280, 807));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuIRecepcionMercaderiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIRecepcionMercaderiasActionPerformed
        RecepcionDirectaMercaderias recepcion = new RecepcionDirectaMercaderias(new JFrame(), true);
        recepcion.pack();
        recepcion.setVisible(true);
    }//GEN-LAST:event_jMnuIRecepcionMercaderiasActionPerformed

    private void jMnuIReImpresionRecepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIReImpresionRecepcionActionPerformed
        InformeReImpresionRecepcionMercaderia infoRecepcion = new InformeReImpresionRecepcionMercaderia(new JFrame(), true);
        infoRecepcion.pack();
        infoRecepcion.setVisible(true);
    }//GEN-LAST:event_jMnuIReImpresionRecepcionActionPerformed

    private void jMnuIArticulosConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIArticulosConsultaActionPerformed
        Articulos articulos = new Articulos(new JFrame(), true, "ABASTECIMIENTO", "");
        articulos.pack();
        articulos.setVisible(true);
    }//GEN-LAST:event_jMnuIArticulosConsultaActionPerformed

    private void jMnuIAjusteStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIAjusteStockActionPerformed
        AjusteStock stock = new AjusteStock(new JFrame(), true);
        stock.pack();
        stock.setVisible(true);
    }//GEN-LAST:event_jMnuIAjusteStockActionPerformed

    private void jMnuIReImpresionAjusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIReImpresionAjusteActionPerformed
        InformeReImpresionAjusteStock ajuste = new InformeReImpresionAjusteStock(new JFrame(), true);
        ajuste.pack();
        ajuste.setVisible(true);
    }//GEN-LAST:event_jMnuIReImpresionAjusteActionPerformed

    private void jMnuIRegistroCompraMercaderiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIRegistroCompraMercaderiasActionPerformed
        RegistroCompraMercaderias compra = new RegistroCompraMercaderias(new JFrame(), true);
        compra.pack();
        compra.setVisible(true);
    }//GEN-LAST:event_jMnuIRegistroCompraMercaderiasActionPerformed

    private void jMnuIRegistroComprobantesGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIRegistroComprobantesGastosActionPerformed
        RegistroComprobanteGastos gastos = new RegistroComprobanteGastos(new JFrame(), true);
        gastos.pack();
        gastos.setVisible(true);
    }//GEN-LAST:event_jMnuIRegistroComprobantesGastosActionPerformed

    private void jMnuIComprasGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIComprasGastosActionPerformed
        InformeComprasGastos compras = new InformeComprasGastos(new JFrame(), true);
        compras.pack();
        compras.setVisible(true);
    }//GEN-LAST:event_jMnuIComprasGastosActionPerformed

    private void jMnuIListadoArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIListadoArticulosActionPerformed
        InformeArticulos articulos = new InformeArticulos(new JFrame(), true);
        articulos.pack();
        articulos.setVisible(true);
    }//GEN-LAST:event_jMnuIListadoArticulosActionPerformed

    private void jMnuIAnulacionDocCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuIAnulacionDocCompraActionPerformed
        AnulacionDocCompraGasto anulacion = new AnulacionDocCompraGasto(new JFrame(), true);
        anulacion.pack();
        anulacion.setVisible(true);
    }//GEN-LAST:event_jMnuIAnulacionDocCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAbastecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAbastecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAbastecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAbastecimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FormAbastecimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnuConsultas;
    private javax.swing.JMenuItem jMnuIAjusteStock;
    private javax.swing.JMenuItem jMnuIAnulacionDocCompra;
    private javax.swing.JMenuItem jMnuIArticulosConsulta;
    private javax.swing.JMenuItem jMnuIComprasGastos;
    private javax.swing.JMenuItem jMnuIListadoArticulos;
    private javax.swing.JMenuItem jMnuIReImpresionAjuste;
    private javax.swing.JMenuItem jMnuIReImpresionRecepcion;
    private javax.swing.JMenuItem jMnuIRecepcionMercaderias;
    private javax.swing.JMenuItem jMnuIRegistroCompraMercaderias;
    private javax.swing.JMenuItem jMnuIRegistroComprobantesGastos;
    private javax.swing.JMenu jMnuInformesAbastecimiento;
    private javax.swing.JMenu jMnuOperacionesAbastecimiento;
    private javax.swing.JMenu jMnuStock;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
