/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModRegistros;

import beans.GrupoBean;
import controls.CentroCostoCtrl;
import controls.GrupoCtrl;
import controls.RubroCtrl;
import controls.UsuarioCtrl;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import principal.FormMain;
import utiles.DBManager;
import utiles.Focus;
import utiles.InfoErrores;
import utiles.MaxLength;
import utiles.TableGrid;
import utiles.Utiles;
import views.busca.BuscaGrupo;

/**
 *
 * @author Andres
 */
public class Grupos extends javax.swing.JDialog {

    /***PENDIENTES
     *  
    */
    
    /**
     * Creates new form Grupos
     */
    private ResultSet resultSetLineas = null;
    private TableGrid tGrid = new TableGrid(null);
    private Vector colLineas = new Vector();
    boolean esNuevo = false;
    
    public Grupos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        configuraCampos();
        if(!Articulos.callFromArticulo){
            cargaGrupo(); // ultimo grupo registrado
        }else{
            cargaGrupoCall(Articulos.jTFCodGrupo.getText());
        }
        
        jSPSubGrupos.getViewport().add(tGrid, null);
        cargaLinea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTFNombreGrupo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFCodCentroCosto = new javax.swing.JTextField();
        jLDescripcionCentroCosto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFCodRubro = new javax.swing.JTextField();
        jLDescripcionRubro = new javax.swing.JLabel();
        jTFCodGrupo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jBAgregarSubGrupo = new javax.swing.JButton();
        jBModificarSubGrupo = new javax.swing.JButton();
        jSPSubGrupos = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jBNuevo = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTFNombreUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTFFecVigencia = new javax.swing.JTextField();

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Mantenimiento de Artículos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ATOMSystems|Main - Mantenimiento de Grupos y SubGrupos");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("MANTENIMIENTO DE GRUPOS Y SUBGRUPOS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel3.setText("Grupo:");

        jTFNombreGrupo.setEnabled(false);
        jTFNombreGrupo.setPreferredSize(new java.awt.Dimension(59, 25));
        jTFNombreGrupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFNombreGrupoFocusGained(evt);
            }
        });
        jTFNombreGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFNombreGrupoKeyPressed(evt);
            }
        });

        jLabel4.setText("Centro de costo:");

        jTFCodCentroCosto.setEnabled(false);
        jTFCodCentroCosto.setPreferredSize(new java.awt.Dimension(59, 25));
        jTFCodCentroCosto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFCodCentroCostoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFCodCentroCostoFocusLost(evt);
            }
        });
        jTFCodCentroCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCodCentroCostoKeyPressed(evt);
            }
        });

        jLDescripcionCentroCosto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLDescripcionCentroCosto.setText("***");

        jLabel6.setText("Rubro:");

        jTFCodRubro.setEnabled(false);
        jTFCodRubro.setPreferredSize(new java.awt.Dimension(6, 25));
        jTFCodRubro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFCodRubroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFCodRubroFocusLost(evt);
            }
        });
        jTFCodRubro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCodRubroKeyPressed(evt);
            }
        });

        jLDescripcionRubro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLDescripcionRubro.setText("***");

        jTFCodGrupo.setEnabled(false);
        jTFCodGrupo.setPreferredSize(new java.awt.Dimension(6, 25));
        jTFCodGrupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFCodGrupoFocusGained(evt);
            }
        });
        jTFCodGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCodGrupoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTFCodRubro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFCodCentroCosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTFCodGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLDescripcionCentroCosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLDescripcionRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTFNombreGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFNombreGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCodGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFCodCentroCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDescripcionCentroCosto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTFCodRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLDescripcionRubro))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "SubGrupos"));

        jBAgregarSubGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nuevo32.png"))); // NOI18N
        jBAgregarSubGrupo.setText("Agregar");
        jBAgregarSubGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarSubGrupoActionPerformed(evt);
            }
        });

        jBModificarSubGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/modificar32.png"))); // NOI18N
        jBModificarSubGrupo.setText("Modificar");
        jBModificarSubGrupo.setPreferredSize(new java.awt.Dimension(73, 60));
        jBModificarSubGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarSubGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSPSubGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAgregarSubGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(jBModificarSubGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSPSubGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jBAgregarSubGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBModificarSubGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Opciones"));

        jBNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nuevo24.png"))); // NOI18N
        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelar24.png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.setEnabled(false);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/modificar24.png"))); // NOI18N
        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/guardar24.png"))); // NOI18N
        jBGuardar.setText("Guardar");
        jBGuardar.setEnabled(false);
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buscar24.png"))); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/salir24.png"))); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jBNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBCancelar))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jBModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBGuardar))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jBBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBBuscar, jBCancelar, jBGuardar, jBModificar, jBNuevo, jBSalir});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo)
                    .addComponent(jBCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBModificar)
                    .addComponent(jBGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBBuscar)
                    .addComponent(jBSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBBuscar, jBCancelar, jBGuardar, jBModificar, jBNuevo, jBSalir});

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Últimas modificaciones"));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel5.setText("Usuario:");

        jTFNombreUsuario.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel7.setText("Fecha:");

        jTFFecVigencia.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFNombreUsuario)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTFFecVigencia))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFFecVigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(814, 555));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        esNuevo = true;
        setComponentesNuevo();        
        jTFCodGrupo.setText(obtenerCodigoGrupo());
        jTFCodCentroCosto.setText("1");
        jTFCodRubro.setText("1");
        jLDescripcionCentroCosto.setText("");
        jLDescripcionRubro.setText("");
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        esNuevo = false;
        setComponentesCancelar();
        cargaGrupo();
        cargaLinea();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jTFNombreGrupoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNombreGrupoFocusGained
        jTFNombreGrupo.selectAll();
    }//GEN-LAST:event_jTFNombreGrupoFocusGained

    private void jTFNombreGrupoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreGrupoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTFCodCentroCosto.grabFocus();
        }
    }//GEN-LAST:event_jTFNombreGrupoKeyPressed

    private void jTFCodCentroCostoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodCentroCostoFocusGained
        jTFCodCentroCosto.selectAll();
    }//GEN-LAST:event_jTFCodCentroCostoFocusGained

    private void jTFCodCentroCostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodCentroCostoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTFCodRubro.grabFocus();
        }
    }//GEN-LAST:event_jTFCodCentroCostoKeyPressed

    private void jTFCodRubroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodRubroFocusGained
        jTFCodRubro.selectAll();
    }//GEN-LAST:event_jTFCodRubroFocusGained

    private void jTFCodRubroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodRubroKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jBGuardar.grabFocus();
        }
    }//GEN-LAST:event_jTFCodRubroKeyPressed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        if(!jTFNombreGrupo.getText().trim().equals("")){
            grabarGrupo();
        }else{
            JOptionPane.showMessageDialog(this, "ATENCION: Debe llenar el campo descripción del grupo !!!", "Error", JOptionPane.WARNING_MESSAGE);
            jTFNombreGrupo.grabFocus();
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jTFCodGrupoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodGrupoFocusGained
        jTFCodGrupo.selectAll();
    }//GEN-LAST:event_jTFCodGrupoFocusGained

    private void jTFCodGrupoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodGrupoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTFNombreGrupo.grabFocus();
        }
    }//GEN-LAST:event_jTFCodGrupoKeyPressed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        esNuevo = false;
        setComponentesEditar();
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jTFCodCentroCostoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodCentroCostoFocusLost
        jLDescripcionCentroCosto.setText(getDescripcionCentroCosto(jTFCodCentroCosto.getText().trim()));
    }//GEN-LAST:event_jTFCodCentroCostoFocusLost

    private void jTFCodRubroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodRubroFocusLost
        jLDescripcionRubro.setText(getDescripcionRubro(jTFCodRubro.getText().trim()));
    }//GEN-LAST:event_jTFCodRubroFocusLost

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        BuscaGrupo bGrupo = new BuscaGrupo(new JFrame(), true);
        bGrupo.pack();
        bGrupo.setVisible(true);
        if (bGrupo.codigo != 0) {
            getGrupo(bGrupo.codigo);
            cargaLinea();
        }
        jBModificar.grabFocus();
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBModificarSubGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarSubGrupoActionPerformed
        try {
            String subGrupoCod1 = String.valueOf( tGrid.getValueAt( tGrid.getSelectedRow(), 0));
            String subGrupoNom1 = String.valueOf( tGrid.getValueAt( tGrid.getSelectedRow(), 1));
            String grupoCod1    = String.valueOf( tGrid.getValueAt( tGrid.getSelectedRow(), 2));
            
            abmLineas(subGrupoCod1, subGrupoNom1, grupoCod1, "Modificar SubGrupo", 2);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "ATENCION: Operacion Fallida... !!!, Debe Seleccionar un Codigo anter de Eliminarlo.", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jBModificarSubGrupoActionPerformed

    private void jBAgregarSubGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarSubGrupoActionPerformed
        abmLineas("", "", jTFCodGrupo.getText(), "Ingreso de SubGrupos", 1);
    }//GEN-LAST:event_jBAgregarSubGrupoActionPerformed

    private void abmLineas(String codSubGrupo, String nombreSubGrupo, String codGrupo, String titulo, int operacion){
        Integer ZERO = new Integer(0);
        esNuevo = false;
        JTextField jTSubGrupoCod;
        JTextField jTSubGrupoNom;
        JTextField jTMargenBase ;
        JTextField jTGrupoCod;
        
        int resultDML = -1; // Para saber si el operador presiono CANCEL
        JPanel pingLinea = new JPanel(new GridLayout(8,2));
        ResultSet rset = null;
        String ultCod = null;
        
        if(operacion == 1){
            rset = DBManager.ejecutarDSL("SELECT MAX(cod_subgrupo) FROM subgrupo WHERE cod_grupo = " + jTFCodGrupo.getText().trim() + "");
            if(rset != null){
                try{
                    rset.next();
                    ultCod = rset.getString(1);
                }catch(SQLException sqlex){
                    sqlex.printStackTrace();
                    ultCod = null;
                }
            }
            if(ultCod == null){
                ultCod = codGrupo + Utiles.padLeft(3, "0", "1");
            }else{
                ultCod = String.valueOf(Integer.parseInt(ultCod) + 1);
            }
            
            jTSubGrupoCod    = new JTextField(ultCod);
            jTSubGrupoNom    = new JTextField(nombreSubGrupo);
            jTGrupoCod       = new JTextField(codGrupo);
            jTMargenBase     = new JTextField("30");
            
            
            pingLinea.add(new JLabel("Codigo de SubGrupo"));
            pingLinea.add(jTSubGrupoCod);
            jTSubGrupoCod.setEditable(false);
            pingLinea.add(new JLabel("Descripcion:"));
            pingLinea.add(jTSubGrupoNom);
            jTSubGrupoNom.setDocument(new MaxLength(40, "UPPER", "ALFA"));
            jTSubGrupoNom.requestFocus();
            pingLinea.add(new JLabel("Margen Base:"));
            pingLinea.add(jTMargenBase);
            jTMargenBase.setDocument(new MaxLength(6, "", "DOUBLE"));
            pingLinea.add(new JLabel("Codigo de Grupo"));
            pingLinea.add(jTGrupoCod);
            jTGrupoCod.setEditable(false);
        }else{
            jTSubGrupoCod    = new JTextField(codSubGrupo);
            jTSubGrupoNom    = new JTextField(nombreSubGrupo);
            jTGrupoCod       = new JTextField(codGrupo);
            jTMargenBase     = new JTextField();
            pingLinea.add(new JLabel("Codigo de SubGrupo"));
            pingLinea.add(jTSubGrupoCod);
            jTSubGrupoCod.setEditable(false);
            pingLinea.add(new JLabel("Descripcion:"));
            jTSubGrupoNom.setDocument(new MaxLength(40, "UPPER", "ALFA"));
            jTSubGrupoNom.setText(nombreSubGrupo);
            pingLinea.add(jTSubGrupoNom);
            jTSubGrupoNom.setEditable(true);
            pingLinea.add(new JLabel("Margen Base:"));
            jTMargenBase.setDocument(new MaxLength(6,"", "DOUBLE"));
            String margenBase    = String.valueOf( tGrid.getValueAt( tGrid.getSelectedRow(), 3));
            jTMargenBase.setText(margenBase);
            pingLinea.add(jTMargenBase);            
            pingLinea.add(new JLabel("Codigo de Grupo"));
            pingLinea.add(jTGrupoCod);
            jTGrupoCod.setEditable(false);
        }
        
        Integer result = new Integer(JOptionPane.showConfirmDialog(this, pingLinea, titulo, JOptionPane.OK_CANCEL_OPTION));
        try{
            if(result.equals(ZERO)){ // Presionó OK
                if(jTSubGrupoNom.getText().equals("") || jTMargenBase.getText().equals("")){
                    JOptionPane.showMessageDialog(this,"Complete los campos requeridos", "Error...", JOptionPane.WARNING_MESSAGE);
                }else{
                    switch(operacion){
                        case 1: resultDML = DBManager.ejecutarDML("INSERT INTO subgrupo (cod_subgrupo, descripcion, cod_grupo, margen_base_vta, fec_vigencia, "
                            + "cod_usuario, margen_trasferencia, es_contabilizado, desc_trasferencia) "
                            + "VALUES  (" + jTSubGrupoCod.getText() + ", '"
                                          + jTSubGrupoNom.getText() + "', "
                                          + jTGrupoCod.getText().toUpperCase() + ", "
                                          + jTMargenBase.getText() + ", '"
                                          + "now()', "
                                          + FormMain.codUsuario + ", "
                                          + "0, '"
                                          + "N', "
                                          + "0)");
                            System.out.println("SQL INSERT: " + "INSERT INTO subgrupo (cod_subgrupo, descripcion, cod_grupo, margen_base_vta, fec_vigencia, "
                                             + "cod_usuario, margen_trasferencia, es_contabilizado, desc_trasferencia) "
                                             + "VALUES (" + jTSubGrupoCod.getText() + ", '"
                                             + jTSubGrupoNom.getText() + "', "
                                             + jTGrupoCod.getText().toUpperCase() + ", "
                                             + jTMargenBase.getText() + ", '"
                                             + "now()', "
                                             + FormMain.codUsuario + ", "
                                             + "0, '"
                                             + "N', "
                                             + "0");
                        break;
                
                    case 2: 
                            resultDML = DBManager.ejecutarDML("UPDATE subgrupo SET "
                            + "descripcion = '" + jTSubGrupoNom.getText() + "', "
                            + "cod_grupo = " + jTGrupoCod.getText().toUpperCase() + ", "
                            + "margen_base_vta = 0, "
                            + "fec_vigencia = 'now()', "
                            + "cod_usuario = " + FormMain.codUsuario + ", "
                            + "margen_trasferencia = 0, "
                            + "es_contabilizado = 'N', "
                            + "desc_trasferencia = 0 "
                            + "WHERE cod_subgrupo = " + jTSubGrupoCod.getText() + " AND cod_grupo = " + jTGrupoCod.getText() + "");

                        System.out.println("SQL UPDATE: " + "UPDATE subgrupo SET "
                                                          + "descripcion = '" + jTSubGrupoCod.getText() + "', "
                                                          + "cod_grupo = '" + jTGrupoCod.getText().toUpperCase() + "', "
                                                          + "margen_base_vta = 0, "
                                                          + "fec_vigencia = 'now()', "
                                                          + "cod_usuario = " + FormMain.codUsuario + ", "
                                                          + "margen_trasferencia = 0, "
                                                          + "es_contabilizado = 'N', "
                                                          + "desc_trasferencia = 0)");
                        break;
                    default : JOptionPane.showMessageDialog(this,"Codigo de Operacion Invalido", "Error...", JOptionPane.WARNING_MESSAGE);
                    }
                }            
             }else{} // CANCEL
        }catch(Exception ex){
            ex.printStackTrace();
            InfoErrores.errores(ex);
        }
        
        
        if(resultDML != 0){
            if(resultDML == 1){
                JOptionPane.showMessageDialog(this, "Operacion Exitosa !!!");
                try{
                    DBManager.conn.commit();
                }catch(SQLException sqlex){
                    sqlex.printStackTrace();
                }
            }
        }else{
            JOptionPane.showMessageDialog(this, "ATENCION: Operacion Fallida... !!!", "Error...", JOptionPane.WARNING_MESSAGE);
        }
        DBManager.CerrarStatements();
        cargaLinea();
    }
    
    private void cargaLinea(){
        if(colLineas.isEmpty()){
            colLineas.addElement("Código");
            colLineas.addElement("Descripción");
            colLineas.addElement("Cod Grupo");
            colLineas.addElement("Margen");
        }
        String sql = "SELECT cod_subgrupo, descripcion, cod_grupo, margen_base_vta "
                   + "FROM subgrupo WHERE cod_grupo = " + jTFCodGrupo.getText().trim() + " "
                   + "ORDER BY cod_subgrupo";
        resultSetLineas = DBManager.ejecutarDSL(sql);
        tGrid.setDataSet(resultSetLineas, colLineas);
        tGrid.setVisible(true);
        tGrid.repaint();
    }
    
    private void grabarGrupo(){
        try{
            String fecVigencia = "";
            try{
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss a");
                java.util.Date d = new java.util.Date();
                fecVigencia = sdf.format(d);
            }catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error Formatando Fecha...");
            }
            
            GrupoBean grupo = new GrupoBean();
            grupo.setCodCentroCosto(Integer.valueOf(jTFCodCentroCosto.getText().trim()));
            grupo.setCodGrupo(Integer.valueOf(jTFCodGrupo.getText().trim()));
            grupo.setCodRubro(Integer.valueOf(jTFCodRubro.getText().trim()));
            grupo.setCodUsuario(FormMain.codUsuario);
            grupo.setDescripcion(jTFNombreGrupo.getText().trim());
            grupo.setEsMateriaPrima("N");
            grupo.setFecVigencia(fecVigencia);
            grupo.setMargenBaseVenta(0);
            
            GrupoCtrl grupoCtrl = new GrupoCtrl();
            if(esNuevo){
                if(grupoCtrl.catastraGrupo(grupo)){
                    JOptionPane.showMessageDialog(this, "Grupo Registrado con Suceso !!!", "OK", JOptionPane.INFORMATION_MESSAGE);
                    setComponentesGrabado();
                    cargaGrupo();
                }else{
                    JOptionPane.showMessageDialog(this, "ATENCION: Error al Registrar Grupo !!!", "Error", JOptionPane.WARNING_MESSAGE);
                }
            }else{ //modificación
                if(grupoCtrl.modificaGrupo(grupo)){
                    JOptionPane.showMessageDialog(this, "Grupo Modificado con Suceso !!!", "OK", JOptionPane.INFORMATION_MESSAGE);
                    setComponentesGrabado();
                    cargaGrupo();
                }else{
                    JOptionPane.showMessageDialog(this, "ATENCION: Error al Modificar Grupo !!!", "Error", JOptionPane.WARNING_MESSAGE);
                }                    
            }
        }catch(Exception ex){
            ex.printStackTrace();
            InfoErrores.errores(ex);
            JOptionPane.showMessageDialog(this, "ATENCION: Error al grabar Grupo !!!", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void configuraCampos(){
        jTFNombreGrupo.setDocument(new MaxLength(30, "UPPER", "ALFA"));
        jTFCodCentroCosto.setDocument(new MaxLength(3, "", "ENTERO"));
        jTFCodRubro.setDocument(new MaxLength(3, "", "ENTERO"));
        
        jTFNombreGrupo.addFocusListener(new Focus());
        jTFCodCentroCosto.addFocusListener(new Focus());
        jTFCodRubro.addFocusListener(new Focus());
    }
    
    private String obtenerCodigoGrupo(){        
        GrupoCtrl grupoCtrl = new GrupoCtrl();
        int result = grupoCtrl.buscaMaxCodGrupo();
        result = result + 1;
        return String.valueOf(result);
    }
    
    private void cargaGrupo(){
        GrupoCtrl grupo = new GrupoCtrl();
        int max = grupo.buscaMaxCodGrupo();
        if(max > 0){
            getGrupo(max);
        }else{
            jBModificar.setEnabled(false);
        }
    }
    
    private void cargaGrupoCall(String codigo){
        
        getGrupo(Integer.valueOf(codigo));
    }
    
    private void getGrupo(int codGrupo){
        GrupoCtrl grupoCtrl = new GrupoCtrl();
        GrupoBean grupoBean = grupoCtrl.buscaGrupoCodigo(codGrupo);
        if(grupoBean != null){
            jTFCodGrupo.setText(String.valueOf(grupoBean.getCodGrupo()));
            jTFNombreGrupo.setText(grupoBean.getDescripcion());
            
            jTFCodCentroCosto.setText(String.valueOf(grupoBean.getCodCentroCosto()));
            jLDescripcionCentroCosto.setText(getDescripcionCentroCosto(jTFCodCentroCosto.getText().trim()));
            
            jTFCodRubro.setText(String.valueOf(grupoBean.getCodRubro()));
            jLDescripcionRubro.setText(getDescripcionRubro(jTFCodRubro.getText().trim()));
            
            jTFFecVigencia.setText(grupoBean.getFecVigencia());
            jTFNombreUsuario.setText(grupoBean.getCodUsuario() + "  -  " + getNombreUsuario(String.valueOf(grupoBean.getCodUsuario())));
        }
    }
    
    private String getNombreUsuario(String codGrupo){
        String result = "";
        if(Utiles.isIntegerValid(codGrupo)){
            UsuarioCtrl usuarioCtrl = new UsuarioCtrl();
            result = usuarioCtrl.getNombreUsuario(Integer.valueOf(codGrupo));
            usuarioCtrl = null;
        }
        return result;
    }
    
    private String getDescripcionRubro(String codigo) {
        String result = "";
        if (Utiles.isIntegerValid(codigo)) {
            RubroCtrl ctrl = new RubroCtrl();
            result = ctrl.getDescripcionGrupo(Integer.valueOf(codigo));
            ctrl = null;
        }
        return result;
    }
    
    private String getDescripcionCentroCosto(String codigo) {
        String result = "";
        if (Utiles.isIntegerValid(codigo)) {
            CentroCostoCtrl ctrl = new CentroCostoCtrl();
            result = ctrl.getNombreCentroCosto(Integer.valueOf(codigo));
            ctrl = null;
        }
        return result;
    }
    
    private void setComponentesEditar(){
        jTFNombreGrupo.setEnabled(true);
        jTFCodCentroCosto.setEnabled(true);
        jTFCodRubro.setEnabled(true);
        jTFCodGrupo.setEnabled(false);
        
        jBNuevo.setEnabled(false);
        jBModificar.setEnabled(false);
        jBBuscar.setEnabled(false);
        jBSalir.setEnabled(false);
        jBCancelar.setEnabled(true);
        jBGuardar.setEnabled(true);
        jTFNombreGrupo.grabFocus();
        jTFNombreGrupo.selectAll();
    }
    
    private void setComponentesCancelar(){
        jTFNombreGrupo.setEnabled(false);
        jTFCodCentroCosto.setEnabled(false);
        jTFCodRubro.setEnabled(false);
        
        jBNuevo.setEnabled(true);
        jBModificar.setEnabled(true);
        jBBuscar.setEnabled(true);
        jBSalir.setEnabled(true);
        jBCancelar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBNuevo.grabFocus();
    }
    
    private void setComponentesNuevo(){
        jTFNombreGrupo.setEnabled(true);
        jTFCodCentroCosto.setEnabled(true);
        jTFCodRubro.setEnabled(true);
        jTFCodGrupo.setText("");
        jTFNombreGrupo.setText("");
        jTFCodCentroCosto.setText("");
        jTFCodRubro.setText("");
        jTFNombreGrupo.grabFocus();
        tGrid.borraAllLineas();
        
        jBNuevo.setEnabled(false);
        jBModificar.setEnabled(false);
        jBBuscar.setEnabled(false);
        jBSalir.setEnabled(false);
        jBCancelar.setEnabled(true);
        jBGuardar.setEnabled(true);
    }
    
    private void setComponentesGrabado(){
        jTFNombreGrupo.setEnabled(false);
        jTFCodCentroCosto.setEnabled(false);
        jTFCodRubro.setEnabled(false);
        jTFCodGrupo.setEnabled(false);
        
        jBNuevo.setEnabled(true);
        jBModificar.setEnabled(true);
        jBBuscar.setEnabled(true);
        jBSalir.setEnabled(true);
        jBCancelar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBNuevo.grabFocus();                
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Grupos dialog = new Grupos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarSubGrupo;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBModificarSubGrupo;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLDescripcionCentroCosto;
    private javax.swing.JLabel jLDescripcionRubro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jSPSubGrupos;
    private javax.swing.JTextField jTFCodCentroCosto;
    private javax.swing.JTextField jTFCodGrupo;
    private javax.swing.JTextField jTFCodRubro;
    private javax.swing.JTextField jTFFecVigencia;
    private javax.swing.JTextField jTFNombreGrupo;
    private javax.swing.JTextField jTFNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
