/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModRegistros;

import beans.MarcaBean;
import controls.MarcaCtrl;
import controls.PaisCtrl;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import principal.FormMain;
import utiles.Focus;
import utiles.InfoErrores;
import utiles.MaxLength;
import utiles.Utiles;
import views.busca.BuscaMarca;
import views.busca.DlgConsultas;

/**
 *
 * @author Andres
 */
public class Marcas extends javax.swing.JDialog {

    /**
     * Creates new form Marcas
     */
    
    boolean esNuevo = false;
    
    public Marcas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setConfigCampos();
        cargaMarca();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jBNuevo = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBBuscarCodigo = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFCodPais = new javax.swing.JTextField();
        jTFNombrePais = new javax.swing.JTextField();

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mantenimiento de Proveedores");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ATOMSystems|Main - Marcas");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("MANTENIMIENTO DE MARCAS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Opciones"));

        jBNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nuevo24.png"))); // NOI18N
        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/modificar24.png"))); // NOI18N
        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/guardar24.png"))); // NOI18N
        jBGuardar.setText("Grabar");
        jBGuardar.setEnabled(false);
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jBGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBGuardarKeyPressed(evt);
            }
        });

        jBBuscarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buscar24.png"))); // NOI18N
        jBBuscarCodigo.setText("Buscar");
        jBBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarCodigoActionPerformed(evt);
            }
        });

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelar24.png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.setEnabled(false);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jBCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBCancelarKeyPressed(evt);
            }
        });

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/salir24.png"))); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBuscarCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo)
                    .addComponent(jBModificar)
                    .addComponent(jBGuardar)
                    .addComponent(jBBuscarCodigo)
                    .addComponent(jBCancelar)
                    .addComponent(jBSalir))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setText("Código:");

        jTFCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFCodigo.setEnabled(false);

        jLabel4.setText("Descripción:");

        jTFDescripcion.setEnabled(false);
        jTFDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFDescripcionFocusGained(evt);
            }
        });
        jTFDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDescripcionKeyPressed(evt);
            }
        });

        jLabel5.setText("País de origen:");

        jTFCodPais.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFCodPais.setEnabled(false);
        jTFCodPais.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFCodPaisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFCodPaisFocusLost(evt);
            }
        });
        jTFCodPais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCodPaisKeyPressed(evt);
            }
        });

        jTFNombrePais.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFCodPais, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFNombrePais))
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFCodPais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFNombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(662, 332));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        esNuevo = true;
        setComponentesNuevo();
        llenarCamposRegistro();
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        esNuevo = false;
        setComponentesModificar();
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        if (verificaCampos()) {
            grabarMarca();
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarCodigoActionPerformed
        BuscaMarca bMarca = new BuscaMarca(new JFrame(), true);
        bMarca.pack();
        bMarca.setVisible(true);
        if (bMarca.codigo != 0) {
            getMarca(bMarca.codigo);
        }
        jBModificar.grabFocus();
    }//GEN-LAST:event_jBBuscarCodigoActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        setComponentesCancelar();
        cargaMarca();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBCancelarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelarKeyPressed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jTFDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDescripcionKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTFCodPais.requestFocus();
        }
    }//GEN-LAST:event_jTFDescripcionKeyPressed

    private void jTFCodPaisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodPaisKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jBGuardar.requestFocus();
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            try {
                DlgConsultas grupo = new DlgConsultas(new JFrame(), true);
                grupo.pack();
                grupo.setTitle("Consulta de Pais");
                grupo.dConsultas("pais", "nombre", "cod_ciudad", "nombre", "fec_vigencia", null, "Codigo", "Nombre", "Registro", null);
                grupo.setText(jTFCodPais);
                grupo.setVisible(true);
            } catch (Exception ex) {
                ex.printStackTrace();
                InfoErrores.errores(ex);
                JOptionPane.showMessageDialog(this, "No se pudo crear el Formulario de Consulta!", "ATENCION", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jTFCodPaisKeyPressed

    private void jBGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBGuardarKeyPressed
        jBGuardar.doClick();
    }//GEN-LAST:event_jBGuardarKeyPressed

    private void jTFCodPaisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodPaisFocusLost
        jTFNombrePais.setText(getNombrePais(jTFCodPais.getText().trim()));
    }//GEN-LAST:event_jTFCodPaisFocusLost

    private void jTFDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDescripcionFocusGained
        jTFDescripcion.selectAll();
    }//GEN-LAST:event_jTFDescripcionFocusGained

    private void jTFCodPaisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodPaisFocusGained
        jTFCodPais.selectAll();
    }//GEN-LAST:event_jTFCodPaisFocusGained

    private void grabarMarca(){
        try{
            String fecVigencia = "";
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss a");
                java.util.Date d = new java.util.Date();
                fecVigencia = sdf.format(d);
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error Formateando Fecha...");
            }
            
            MarcaBean mBean = new MarcaBean();
            mBean.setCodMarca(Integer.valueOf(jTFCodigo.getText().trim()));
            mBean.setCodPais(Integer.valueOf(jTFCodPais.getText().trim()));
            mBean.setCodUsuario(FormMain.codUsuario);
            mBean.setDescripcion(jTFDescripcion.getText().trim());
            mBean.setFecVigencia(fecVigencia);
            
            MarcaCtrl mCtrl = new MarcaCtrl();
            if(esNuevo){
                if(mCtrl.catastrarMarca(mBean)){
                    JOptionPane.showMessageDialog(this, "Marca registrada con éxito !!!", "OK", JOptionPane.INFORMATION_MESSAGE);
                    setComponentesGrabado();
                    cargaMarca();
                }else{
                    JOptionPane.showMessageDialog(this, "Error al Registrar Marca !!!", "Error", JOptionPane.INFORMATION_MESSAGE);
                }
            }else{ // modificacion
                if(mCtrl.alterarMarca(mBean)){
                    JOptionPane.showMessageDialog(this, "Marca Modificada con Suceso !!!", "OK", JOptionPane.INFORMATION_MESSAGE);
                    setComponentesGrabado();
                }else{
                    JOptionPane.showMessageDialog(this, "ATENCION: Error al Modificar Marca !!!", "Error", JOptionPane.WARNING_MESSAGE);
                }
            }
        }catch(Exception ex){
            ex.printStackTrace();
            InfoErrores.errores(ex);
            JOptionPane.showMessageDialog(this, "ATENCION: Error al grabar Marca !!!", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void setComponentesGrabado() {

        jTFDescripcion.setEnabled(false);
        jTFCodPais.setEnabled(false);

        jBNuevo.setEnabled(true);
        jBModificar.setEnabled(true);
        jBBuscarCodigo.setEnabled(true);
        jBSalir.setEnabled(true);
        jBCancelar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBNuevo.grabFocus();
    }
    
    private void cargaMarca() {
        MarcaCtrl pCtrl = new MarcaCtrl();
        int max = pCtrl.buscaMaxCodMarca();
        if (max > 0) {
            getMarca(max);
        } else {
            jBModificar.setEnabled(false);
        }
    }
    
    private void getMarca(int codigo) {
        MarcaCtrl pCtrl = new MarcaCtrl();
        MarcaBean pBean = pCtrl.buscaMarcaCodigo(codigo);
        if (pBean != null) {
            jTFCodigo.setText(String.valueOf(pBean.getCodMarca()));
            jTFDescripcion.setText(pBean.getDescripcion());
            jTFCodPais.setText(String.valueOf(pBean.getCodPais()));
            jTFNombrePais.setText(getNombrePais(jTFCodPais.getText().trim()));
        }
    }
    
    private String getNombrePais(String codigo) {
        String result = "";
        if (Utiles.isIntegerValid(codigo)) {
            PaisCtrl ctrl = new PaisCtrl();
            result = ctrl.getNombrePais(Integer.valueOf(codigo));
            ctrl = null;
        }
        return result;
    }
    
    private boolean verificaCampos(){
        if(jTFDescripcion.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "ATENCION: Complete el campo DESCRIPCION !!!", "Error", JOptionPane.WARNING_MESSAGE);
            jTFDescripcion.requestFocus();
            return false;
        }
        return true;
    }
    
    private void setComponentesCancelar() {
        jTFDescripcion.setEnabled(false);
        jTFCodPais.setEnabled(false);
        jBNuevo.grabFocus();

        jBBuscarCodigo.setEnabled(true);
        jBCancelar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBModificar.setEnabled(true);
        jBNuevo.setEnabled(true);
        jBSalir.setEnabled(true);
    }
    
    
    private void setComponentesModificar() {
        jTFDescripcion.setEnabled(true);
        jTFCodPais.setEnabled(true);

        jTFDescripcion.grabFocus();

        jBBuscarCodigo.setEnabled(false);
        jBCancelar.setEnabled(true);
        jBGuardar.setEnabled(true);
        jBModificar.setEnabled(false);
        jBNuevo.setEnabled(true);
        jBSalir.setEnabled(true);
    }
            
    private void setComponentesNuevo() {
        jTFDescripcion.setEnabled(true);
        jTFCodPais.setEnabled(true);

        jTFDescripcion.grabFocus();

        jBBuscarCodigo.setEnabled(false);
        jBCancelar.setEnabled(true);
        jBGuardar.setEnabled(true);
        jBModificar.setEnabled(false);
        jBNuevo.setEnabled(true);
        jBSalir.setEnabled(true);
    }
    
    private void setConfigCampos() {

        jTFDescripcion.setDocument(new MaxLength(40, "UPPER", "ALFA"));
        jTFCodPais.setDocument(new MaxLength(5, "", "ENTERO"));
        
        jTFDescripcion.addFocusListener(new Focus());
        jTFCodPais.addFocusListener(new Focus());
        
    }
    
    private void llenarCamposRegistro() {

        jTFCodigo.setText(getCodigoMarca());
        jTFDescripcion.setText("");
        jTFCodPais.setText("1");
    }
    
    private String getCodigoMarca() {
        MarcaCtrl mCtrl = new MarcaCtrl();
        int result = mCtrl.buscaMaxCodMarca();
        result = result + 1;
        return String.valueOf(result);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Marcas dialog = new Marcas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarCodigo;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTFCodPais;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFDescripcion;
    private javax.swing.JTextField jTFNombrePais;
    // End of variables declaration//GEN-END:variables
}
