/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModRegistros;

import com.sun.glass.events.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import utiles.CellRenderer;
import utiles.DBManager;
import utiles.InfoErrores;
import utiles.StatementManager;

/**
 *
 * @author Andres
 * 
 * -- PENDIENTES 
 * 1. Grabar precios de ventas 
 */
public class PrecioVenta extends javax.swing.JDialog {

    DefaultTableModel dtm = new DefaultTableModel(null, new String[]{"Lista", "Lista Precio", "Sigla", "U/M", "Margen", "Precio", "Fec Vig", "Usuario"});
    private final DecimalFormat decimalFormat = new DecimalFormat("###,###,###.00");
    String codArticulo;
    private ResultSet rs = null;
    
    /**
     * Creates new form PrecioVenta
     */
    public PrecioVenta(java.awt.Frame parent, boolean modal, long codArt, String codLista) {
        super(parent, modal);
        initComponents();
        
        configComponentesInicio();
        codArticulo = String.valueOf(codArt);
        getDescArt(codArt);
        cargaComboLista();
        cargaComboSigla();
        configuraTabla();
        cargarPrecioVentaEnTabla();
        getCostoArt(codArt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLDescripcion = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCBListaPrecio = new javax.swing.JComboBox<>();
        jLDescListaPrecio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCBSiglaVenta = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTFUM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFMargen = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTFPrecioVenta = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFCostoNeto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFCostoUnitario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFEmpaqueCompra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTFUMCompra = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTPrecios = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jBCancelar = new javax.swing.JButton();
        jBConfirmar = new javax.swing.JButton();
        jBNuevo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ATOMSystems|Main - Mantenimiento de Precios de Venta ");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLDescripcion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLDescripcion.setText("***");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLDescripcion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Lista de Precio:");

        jCBListaPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBListaPrecioActionPerformed(evt);
            }
        });
        jCBListaPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCBListaPrecioKeyPressed(evt);
            }
        });

        jLDescListaPrecio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLDescListaPrecio.setText("***");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Sigla de Venta:");

        jCBSiglaVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCBSiglaVentaKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("U/M:");

        jTFUM.setEditable(false);
        jTFUM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFUM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFUMFocusGained(evt);
            }
        });
        jTFUM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFUMKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Margen:");

        jTFMargen.setEditable(false);
        jTFMargen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFMargen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFMargenFocusGained(evt);
            }
        });
        jTFMargen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFMargenKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText(" %");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Precio de Venta:");

        jTFPrecioVenta.setEditable(false);
        jTFPrecioVenta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTFPrecioVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFPrecioVentaFocusGained(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Precio de Costo");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Costo Neto:");

        jTFCostoNeto.setEditable(false);
        jTFCostoNeto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Costo Unitario:");

        jTFCostoUnitario.setEditable(false);
        jTFCostoUnitario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Empaque Compra:");

        jTFEmpaqueCompra.setEditable(false);
        jTFEmpaqueCompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("U/M:");

        jTFUMCompra.setEditable(false);
        jTFUMCompra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTFMargen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jTFUM, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTFPrecioVenta, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCBListaPrecio, javax.swing.GroupLayout.Alignment.LEADING, 0, 112, Short.MAX_VALUE)
                            .addComponent(jCBSiglaVenta, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLDescListaPrecio)))
                .addGap(65, 65, 65)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFCostoNeto)
                            .addComponent(jTFCostoUnitario)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTFEmpaqueCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFUMCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(189, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jCBListaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLDescListaPrecio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jCBSiglaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTFUM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTFMargen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTFPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFEmpaqueCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jTFUMCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTFCostoNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTFCostoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Precios de Ventas por Lista"));

        jTPrecios = new JTable(){

            public boolean isCellEditable(int rowIndex, int colIndex) {

                /* if(colIndex == 4){ // La 4ta columna isEditable(true)
                    return true;
                }else{
                    return false; //Las celdas no son editables.
                }*/
                return false; //Las celdas no son editables.
            }
        };
        jTPrecios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTPrecios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTPrecios);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelar24.png"))); // NOI18N
        jBCancelar.setMnemonic('C');
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/check24.png"))); // NOI18N
        jBConfirmar.setMnemonic('N');
        jBConfirmar.setText("Confirmar");

        jBNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nuevo24.png"))); // NOI18N
        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBConfirmar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCancelar)
                .addContainerGap())
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBCancelar, jBConfirmar, jBNuevo});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo)
                    .addComponent(jBCancelar)
                    .addComponent(jBConfirmar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBCancelar, jBConfirmar, jBNuevo});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(799, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCBListaPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBListaPrecioActionPerformed
        jLDescListaPrecio.setText(utiles.Utiles.getInfoListaPrecio("descripcion", jCBListaPrecio.getSelectedItem().toString()));
    }//GEN-LAST:event_jCBListaPrecioActionPerformed

    private void jCBListaPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBListaPrecioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jCBSiglaVenta.grabFocus();
        }
    }//GEN-LAST:event_jCBListaPrecioKeyPressed

    private void jCBSiglaVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCBSiglaVentaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTFUM.grabFocus();
        }
    }//GEN-LAST:event_jCBSiglaVentaKeyPressed

    private void jTFUMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFUMKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTFMargen.grabFocus();
        }
    }//GEN-LAST:event_jTFUMKeyPressed

    private void jTFMargenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFMargenKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTFPrecioVenta.grabFocus();
        }
    }//GEN-LAST:event_jTFMargenKeyPressed

    private void jTFUMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFUMFocusGained
        jTFUM.selectAll();
    }//GEN-LAST:event_jTFUMFocusGained

    private void jTFMargenFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFMargenFocusGained
        jTFMargen.selectAll();
    }//GEN-LAST:event_jTFMargenFocusGained

    private void jTFPrecioVentaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFPrecioVentaFocusGained
        jTFPrecioVenta.selectAll();
    }//GEN-LAST:event_jTFPrecioVentaFocusGained

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        setComponentesNuevo();
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void setComponentesNuevo(){
        jTFUM.setEditable(true);
        jTFMargen.setEditable(true);
        jTFPrecioVenta.setEditable(true);
        jCBListaPrecio.grabFocus();
        
    }
    
    private void cargaComboLista(){
        StatementManager TheQuery = new StatementManager();
        TheQuery.TheSql = "select cod_lista from listaprecio";
        TheQuery.EjecutarSql();
        try {
            while (TheQuery.TheResultSet.next()) {
                try {                    
                    jCBListaPrecio.addItem(TheQuery.TheResultSet.getString("cod_lista"));                   
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    InfoErrores.errores(ex);
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            InfoErrores.errores(ex);
        } finally {
            DBManager.CerrarStatements();
        }
        TheQuery.CerrarStatement();
        TheQuery = null;
    }
    
    private boolean getCostoArt(long codArt){
        boolean result = true;
        StatementManager sm = new StatementManager();
        try{
            sm.TheSql = "SELECT sigla_compra, cansi_compra, costo_bruto, costo_neto, costo_promedio, descuento_pct, fec_vigencia "
                      + "FROM costoart WHERE cod_articulo = " + codArt + " AND vigente = 'S' AND cod_lista = 1";
            sm.EjecutarSql();
            if(sm.TheResultSet.next()){
                jTFCostoNeto.setText(decimalFormat.format(sm.TheResultSet.getInt("costo_neto")));
                jTFCostoUnitario.setText(decimalFormat.format(sm.TheResultSet.getInt("costo_promedio")));
                jTFEmpaqueCompra.setText(sm.TheResultSet.getString("sigla_compra"));
                jTFUMCompra.setText(sm.TheResultSet.getString("cansi_compra"));
            }else{}
        }catch(Exception ex){
            result = false;
            ex.printStackTrace();
            InfoErrores.errores(ex);
        }finally{
            sm.CerrarResultSet();
            sm = null;
        }
        return result;
    }
    
    private void cargarPrecioVentaEnTabla(){
        StatementManager stm = new StatementManager();
        try{
            String sql = ("SELECT preciosart.cod_lista, listaprecio.descripcion, preciosart.sigla_venta, preciosart.cansi_venta, " +
                          "preciosart.precio_venta, to_char(preciosart.fec_vigencia, 'dd/MM/yyyy') AS fecVigencia, usuario.nombre " +
                          "FROM preciosart " +
                          "INNER JOIN listaprecio " +
                          "ON preciosart.cod_lista = listaprecio.cod_lista " +
                          "INNER JOIN usuario " +
                          "ON preciosart.cod_usuario = usuario.cod_usuario " +
                          "WHERE preciosart.vigente = 'S' AND preciosart.cod_articulo = " + codArticulo);
            rs = DBManager.ejecutarDSL(sql);
            
            if(rs != null){
                while(rs.next()){
                    Object[] row = new Object[8];
                    row[0] = rs.getInt("cod_lista");
                    row[1] = rs.getString("descripcion");
                    row[2] = rs.getString("sigla_venta");
                    row[3] = rs.getInt("cansi_venta");
                    row[4] = rs.getInt("cansi_venta");
                    row[5] = rs.getInt("precio_venta");
                    row[6] = rs.getString("fecVigencia");
                    row[7] = rs.getString("nombre");
                    dtm.addRow(row);
                }
                jTPrecios.updateUI();
                
                for(int i = 0; jTPrecios.getRowCount() <= i; i++){
                    jTPrecios.isCellEditable(i, 4);
                }
            }
        }catch(Exception ex){
            ex.printStackTrace();
            InfoErrores.errores(ex);
        }
    }
    
    private void configuraTabla(){
        jTPrecios.setModel(dtm);      
        jTPrecios.setDefaultRenderer(Object.class, new CellRenderer()); // esto le da formato a la tabla dependiendo del valor que tenga (double, string, int)
        
        jTPrecios.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTPrecios.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTPrecios.getColumnModel().getColumn(2).setPreferredWidth(50);
        
        jTPrecios.getColumnModel().getColumn(3).setPreferredWidth(70);
        jTPrecios.getColumnModel().getColumn(4).setPreferredWidth(70);
        jTPrecios.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTPrecios.getColumnModel().getColumn(6).setPreferredWidth(130);
        jTPrecios.getColumnModel().getColumn(7).setPreferredWidth(130);
    }
    
    private void cargaComboSigla() {         
        StatementManager TheQuery = new StatementManager();
        TheQuery.TheSql = "select  sigla from sigla order by descripcion desc";
        TheQuery.EjecutarSql();
        try {
            while (TheQuery.TheResultSet.next()) {
                try {                    
                    jCBSiglaVenta.addItem(TheQuery.TheResultSet.getString("sigla"));                   
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    InfoErrores.errores(ex);
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            InfoErrores.errores(ex);
        } finally {
            DBManager.CerrarStatements();
        }
        TheQuery.CerrarStatement();
        TheQuery = null;
    }
    
    private boolean getDescArt(long codArt) {
        boolean result = true;
        StatementManager sm = new StatementManager();
        try {
            sm.TheSql = "SELECT descripcion "+
                    " FROM articulo "+
                    " WHERE cod_articulo = " + codArt;
            sm.EjecutarSql();
            if (sm.TheResultSet.next()) {
                jLDescripcion.setText(sm.TheResultSet.getString("descripcion"));
            } else {
                jLDescripcion.setText("INEXISTENTE !!!");
            }
        } catch (Exception ex) {
            result = false;
            ex.printStackTrace();
            InfoErrores.errores(ex);
        } finally {
            sm.CerrarStatement();
            sm = null;
        }
        return result;
    }
    
    private void configComponentesInicio(){
        jTFUM.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFMargen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFPrecioVenta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        
        jTFEmpaqueCompra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFUMCompra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFCostoNeto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFCostoUnitario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrecioVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrecioVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrecioVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrecioVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrecioVenta(new javax.swing.JFrame(), true, 0, "1");
                /*PrecioVenta dialog = new PrecioVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBConfirmar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JComboBox<String> jCBListaPrecio;
    private javax.swing.JComboBox<String> jCBSiglaVenta;
    private javax.swing.JLabel jLDescListaPrecio;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFCostoNeto;
    private javax.swing.JTextField jTFCostoUnitario;
    private javax.swing.JTextField jTFEmpaqueCompra;
    private javax.swing.JTextField jTFMargen;
    private javax.swing.JTextField jTFPrecioVenta;
    private javax.swing.JTextField jTFUM;
    private javax.swing.JTextField jTFUMCompra;
    private javax.swing.JTable jTPrecios;
    // End of variables declaration//GEN-END:variables
}
