/*
 * BuscaCiudad.java
 *
 * Created on 14 de noviembre de 2008, 02:13 PM
 */
package views.busca;

import beans.ClienteBean;
import controls.ClienteCtrl;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import utiles.MaxLength;
import utiles.Utiles;

/**
 *
 * @author  Claudio Kunnen
 */
public class BuscaCliente extends javax.swing.JDialog {

    DefaultTableModel dtmClientes = new DefaultTableModel(null, new String[]{"Código", "Razón Social", "RUC", "Teléfono"});
    ListSelectionModel lsmClientes;
    List<ClienteBean> clienteBeanList = new ArrayList();
    public static int codigo = 0;

    /** Creates new form BuscaCiudad */
    public BuscaCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        jtfInputBusca.setDocument(new MaxLength(40, "UPPER", "ALFA"));
        jtfInputBusca.requestFocus();
        clienteBeanList.clear();

        jTClientes.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTClientes.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTClientes.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTClientes.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTClientes.setRowHeight(23);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTClientes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jtfInputBusca = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jrbNombre = new javax.swing.JRadioButton();
        jrbCodigo = new javax.swing.JRadioButton();
        jrbRuc = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jbCancelar = new javax.swing.JButton();
        jbSelecciona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ATOMSystems|Main - Búsqueda de Clientes");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jTClientes.setModel(dtmClientes);
        jTClientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmClientes = jTClientes.getSelectionModel();
        lsmClientes.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (! e.getValueIsAdjusting()){
                    jtCiudadesLinhaSelecionada(jTClientes);
                }
            }
        });
        jTClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTClientesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTClientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jtfInputBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfInputBuscaKeyPressed(evt);
            }
        });

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buscar24.png"))); // NOI18N
        jbBuscar.setMnemonic('B');
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por:"));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel4FocusGained(evt);
            }
        });

        jrbNombre.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(jrbNombre);
        jrbNombre.setSelected(true);
        jrbNombre.setText("Nombre");
        jrbNombre.setFocusable(false);
        jrbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNombreActionPerformed(evt);
            }
        });

        jrbCodigo.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(jrbCodigo);
        jrbCodigo.setText("Código");
        jrbCodigo.setFocusable(false);
        jrbCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCodigoActionPerformed(evt);
            }
        });

        jrbRuc.setBackground(new java.awt.Color(204, 255, 204));
        buttonGroup1.add(jrbRuc);
        jrbRuc.setText("RUC");
        jrbRuc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jrbRucFocusGained(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbRuc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jrbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jrbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jrbRuc))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfInputBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuscar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbBuscar)
                        .addComponent(jtfInputBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelar24.png"))); // NOI18N
        jbCancelar.setMnemonic('C');
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbSelecciona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/seleccionar24.png"))); // NOI18N
        jbSelecciona.setMnemonic('S');
        jbSelecciona.setText("Seleccionar");
        jbSelecciona.setEnabled(false);
        jbSelecciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeleccionaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSelecciona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSelecciona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(646, 439));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    protected void jtCiudadesLinhaSelecionada(JTable tb) {
        if (tb.getSelectedRow() != -1) {
            jbSelecciona.setEnabled(true);
            jbSelecciona.setSelected(true);
        } else {
            jbSelecciona.setEnabled(false);
            jbSelecciona.setSelected(false);
        }
    }

private void jrbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNombreActionPerformed
    jtfInputBusca.requestFocus();
}//GEN-LAST:event_jrbNombreActionPerformed

private void jrbCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCodigoActionPerformed
    jtfInputBusca.requestFocus();
}//GEN-LAST:event_jrbCodigoActionPerformed

private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
    ClienteCtrl clienteCtrl = new ClienteCtrl();
    clienteBeanList.clear();
    if (jrbNombre.isSelected()) {
        clienteBeanList = clienteCtrl.listarClienteRazonSoc("%" + jtfInputBusca.getText().trim() + "%");
    } else if(jrbRuc.isSelected()){
        clienteBeanList = clienteCtrl.listarClienteRuc("%" + jtfInputBusca.getText().trim() + "%");
    }else {
        if (Utiles.isIntegerValid(jtfInputBusca.getText().trim())) {
            clienteBeanList.add(clienteCtrl.buscaClienteCodCliente(Integer.valueOf(jtfInputBusca.getText().trim())));
        }
    }

    if (clienteBeanList.size() > 0) {
        cargaProveedoresGrid(clienteBeanList);
        jTClientes.grabFocus();
    }
}//GEN-LAST:event_jbBuscarActionPerformed

private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
    codigo = 0;
    dispose();
}//GEN-LAST:event_jbCancelarActionPerformed

private void jtfInputBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfInputBuscaKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jbBuscar.doClick();
        if (jTClientes.getRowCount() > 0) {
            jTClientes.grabFocus();
        }
    }
}//GEN-LAST:event_jtfInputBuscaKeyPressed

private void jbSeleccionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeleccionaActionPerformed
    codigo = Integer.parseInt(jTClientes.getValueAt(jTClientes.getSelectedRow(), 0).toString());
    dispose();
}//GEN-LAST:event_jbSeleccionaActionPerformed

private void jTClientesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTClientesKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jbSelecciona.doClick();
    }
}//GEN-LAST:event_jTClientesKeyPressed

    private void jPanel4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel4FocusGained
        jtfInputBusca.requestFocus();
    }//GEN-LAST:event_jPanel4FocusGained

    private void jrbRucFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jrbRucFocusGained
        jtfInputBusca.requestFocus();
    }//GEN-LAST:event_jrbRucFocusGained

    protected void cargaProveedoresGrid(List<ClienteBean> clienteBean){
        while (dtmClientes.getRowCount() > 0){
            dtmClientes.removeRow(0);
        }
        
        if (clienteBean.size() == 0){
            JOptionPane.showMessageDialog(this, "ATENCION: Ningún Cliente Encontrado !!!", "Busca", JOptionPane.INFORMATION_MESSAGE);
        }else{
            String [] campos = new String[] {null, null, null, null};
            for (int i = 0; i < clienteBean.size(); i++){
                dtmClientes.addRow(campos);
                dtmClientes.setValueAt(clienteBean.get(i).getCodCliente(), i, 0);
                dtmClientes.setValueAt(clienteBean.get(i).getRazonSoc(), i, 1);
                dtmClientes.setValueAt(clienteBean.get(i).getRucCliente(), i, 2);
                dtmClientes.setValueAt(clienteBean.get(i).getTelefono(), i, 3);
            }
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscaCliente dialog = new BuscaCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTClientes;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSelecciona;
    private javax.swing.JRadioButton jrbCodigo;
    private javax.swing.JRadioButton jrbNombre;
    private javax.swing.JRadioButton jrbRuc;
    public static javax.swing.JTextField jtfInputBusca;
    // End of variables declaration//GEN-END:variables

}
