/*
 * BuscaCiudad.java
 *
 * Created on 14 de noviembre de 2008, 02:13 PM
 */
package views.busca;

import beans.CiudadBean;
import beans.MarcaBean;
import controls.CiudadCtrl;
import controls.MarcaCtrl;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import utiles.MaxLength;
import utiles.Utiles;

/**
 *
 * @author  Claudio Kunnen
 */
public class BuscaCiudad extends javax.swing.JDialog {

    DefaultTableModel dtmCiudades = new DefaultTableModel(null, new String[]{"Código", "Nombre", "Departamento"});
    ListSelectionModel lsmCiudades;
    List<CiudadBean> ciudadBeanList = new ArrayList();
    public static int codigo = 0;

    /** Creates new form BuscaCiudad */
    public BuscaCiudad(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        jtfInputBusca.setDocument(new MaxLength(40, "UPPER", "ALFA"));

        ciudadBeanList.clear();

        jTCiudades.getColumnModel().getColumn(0).setPreferredWidth(50);
        jTCiudades.getColumnModel().getColumn(1).setPreferredWidth(250);
        jTCiudades.getColumnModel().getColumn(2).setPreferredWidth(120);
        jTCiudades.setRowHeight(23);

        jtfInputBusca.grabFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCiudades = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jtfInputBusca = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jrbNombre = new javax.swing.JRadioButton();
        jrbCodigo = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jbCancelar = new javax.swing.JButton();
        jbSelecciona = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ATOMSystems|Main - Búsqueda de Ciudades");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jTCiudades.setModel(dtmCiudades);
        jTCiudades.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmCiudades = jTCiudades.getSelectionModel();
        lsmCiudades.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (! e.getValueIsAdjusting()){
                    jtCiudadesLinhaSelecionada(jTCiudades);
                }
            }
        });
        jTCiudades.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTCiudadesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTCiudades);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jtfInputBusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfInputBuscaKeyPressed(evt);
            }
        });

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buscar24.png"))); // NOI18N
        jbBuscar.setMnemonic('B');
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por:"));

        jrbNombre.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbNombre);
        jrbNombre.setSelected(true);
        jrbNombre.setText("Nombre");
        jrbNombre.setFocusable(false);
        jrbNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNombreActionPerformed(evt);
            }
        });

        jrbCodigo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbCodigo);
        jrbCodigo.setText("Código");
        jrbCodigo.setFocusable(false);
        jrbCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbCodigo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jrbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jrbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfInputBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbBuscar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbBuscar)
                        .addComponent(jtfInputBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelar24.png"))); // NOI18N
        jbCancelar.setMnemonic('C');
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbSelecciona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/seleccionar24.png"))); // NOI18N
        jbSelecciona.setMnemonic('S');
        jbSelecciona.setText("Seleccionar");
        jbSelecciona.setEnabled(false);
        jbSelecciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeleccionaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(jbSelecciona)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSelecciona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(565, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    protected void jtCiudadesLinhaSelecionada(JTable tb) {
        if (tb.getSelectedRow() != -1) {
            jbSelecciona.setEnabled(true);
            jbSelecciona.setSelected(true);
        } else {
            jbSelecciona.setEnabled(false);
            jbSelecciona.setSelected(false);
        }
    }

private void jrbNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNombreActionPerformed
    jtfInputBusca.requestFocus();
}//GEN-LAST:event_jrbNombreActionPerformed

private void jrbCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbCodigoActionPerformed
    jtfInputBusca.requestFocus();
}//GEN-LAST:event_jrbCodigoActionPerformed

private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
    CiudadCtrl ciudadCtrl = new CiudadCtrl();
    ciudadBeanList.clear();
    if (jrbNombre.isSelected()) {
        ciudadBeanList = ciudadCtrl.listarCiudadNombre("%" + jtfInputBusca.getText().trim() + "%");
    } else {
        if (Utiles.isIntegerValid(jtfInputBusca.getText().trim())) {
            ciudadBeanList.add(ciudadCtrl.buscaCiudadCodCiudad(Integer.valueOf(jtfInputBusca.getText().trim())));
        }
    }

    if (ciudadBeanList.size() > 0) {
        cargaCiudadesGrid(ciudadBeanList);
        jTCiudades.grabFocus();
    }
}//GEN-LAST:event_jbBuscarActionPerformed

private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
    codigo = 0;
    dispose();
}//GEN-LAST:event_jbCancelarActionPerformed

private void jtfInputBuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfInputBuscaKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jbBuscar.doClick();
        if (jTCiudades.getRowCount() > 0) {
            jTCiudades.grabFocus();
        }
    }
}//GEN-LAST:event_jtfInputBuscaKeyPressed

private void jbSeleccionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeleccionaActionPerformed
    codigo = Integer.parseInt(jTCiudades.getValueAt(jTCiudades.getSelectedRow(), 0).toString());
    dispose();
}//GEN-LAST:event_jbSeleccionaActionPerformed

private void jTCiudadesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCiudadesKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        jbSelecciona.doClick();
    }
}//GEN-LAST:event_jTCiudadesKeyPressed

    protected void cargaCiudadesGrid(List<CiudadBean> ciudadBean){
        while (dtmCiudades.getRowCount() > 0){
            dtmCiudades.removeRow(0);
        }
        
        if (ciudadBean.size() == 0){
            JOptionPane.showMessageDialog(this, "ATENCION: Ninguna Ciudad Encontrada !!!", "Busca", JOptionPane.INFORMATION_MESSAGE);
        }else{
            String [] campos = new String[] {null, null, null, null};
            for (int i = 0; i < ciudadBean.size(); i++){
                dtmCiudades.addRow(campos);
                dtmCiudades.setValueAt(ciudadBean.get(i).getCodCiudad(), i, 0);
                dtmCiudades.setValueAt(ciudadBean.get(i).getNombre(), i, 1);
                dtmCiudades.setValueAt(ciudadBean.get(i).getCodDepartamento(), i, 2);
            }
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BuscaCiudad dialog = new BuscaCiudad(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCiudades;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSelecciona;
    private javax.swing.JRadioButton jrbCodigo;
    private javax.swing.JRadioButton jrbNombre;
    private javax.swing.JTextField jtfInputBusca;
    // End of variables declaration//GEN-END:variables

}
