/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.busca;

import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import utiles.DBManager;
import utiles.InfoErrores;
import utiles.MaxLength;

/**
 *
 * @author Andres
 */
public class DlgConsultasCuentasMonedas extends javax.swing.JDialog {

    DefaultTableModel dtm = new DefaultTableModel(null, new String[]{"Código", "Denominación", "Compra", "Activa"});
    private ResultSet rs = null;
    private static JTextField jText;
    
    public DlgConsultasCuentasMonedas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        configTabla();
        jTFDescripcion.setDocument(new MaxLength(35, "UPPER", "ALFA"));
    }

    private void configTabla(){
        jTDetallesCuenta.setModel(dtm);
        jTDetallesCuenta.getColumnModel().getColumn(0).setPreferredWidth(5);
        jTDetallesCuenta.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTDetallesCuenta.getColumnModel().getColumn(2).setPreferredWidth(10);
        jTDetallesCuenta.getColumnModel().getColumn(3).setPreferredWidth(10);
    }
    
    private void limpiarGrillas()
    {
        for (int i = 0; i < jTDetallesCuenta.getRowCount(); i++) {
                dtm.removeRow(i);
                i--;
            }
    }
    
    public static void setText(JTextField jTf)
    {
        jText = jTf;
    }
    
    private void llenarTabla(String texto){
        try{
            limpiarGrillas();
            rs = DBManager.ejecutarDSL("SELECT cod_cuenta, denominacion_cta, moneda.cotiz_compra, cuenta.activa "
                                     + "FROM cuenta "
                                     + "LEFT OUTER JOIN moneda "
                                     + "ON cuenta.cod_moneda = moneda.cod_moneda "
                                     + "WHERE denominacion_cta LIKE '%" + texto + "%' ORDER BY cod_cuenta");
            if(rs != null){
                while(rs.next()){
                    Object[] row = new Object[4];
                    row[0] = rs.getInt("cod_cuenta");
                    row[1] = rs.getString("denominacion_cta");
                    row[2] = rs.getFloat("cotiz_compra");
                    row[3] = rs.getString("activa");
                    dtm.addRow(row);
                }
                jTDetallesCuenta.updateUI();
                jTDetallesCuenta.grabFocus();
            }
        }catch(Exception ex){
            ex.printStackTrace();
            InfoErrores.errores(ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDetallesCuenta = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ATOMSystems|Main - Consulta de Cuenta y Cotización");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Ingrese descripción:");

        jTFDescripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTFDescripcion.setText("%");
        jTFDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFDescripcionFocusGained(evt);
            }
        });
        jTFDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDescripcionKeyPressed(evt);
            }
        });

        jTDetallesCuenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTDetallesCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Denominación", "Compra", "Activa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTDetallesCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTDetallesCuentaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTDetallesCuenta);
        if (jTDetallesCuenta.getColumnModel().getColumnCount() > 0) {
            jTDetallesCuenta.getColumnModel().getColumn(0).setResizable(false);
            jTDetallesCuenta.getColumnModel().getColumn(1).setResizable(false);
            jTDetallesCuenta.getColumnModel().getColumn(2).setResizable(false);
            jTDetallesCuenta.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFDescripcion)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(700, 465));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTFDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDescripcionKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!jTFDescripcion.getText().trim().equals("")){
                llenarTabla(jTFDescripcion.getText().trim());
                if(jTDetallesCuenta.getRowCount() > 0)
                {
                    jTDetallesCuenta.setRowSelectionInterval(0, 0);
                    jTDetallesCuenta.grabFocus();
                }
            }
        }
    }//GEN-LAST:event_jTFDescripcionKeyPressed

    private void jTDetallesCuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTDetallesCuentaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
        {
            jText.setText(String.valueOf(jTDetallesCuenta.getValueAt(jTDetallesCuenta.getSelectedRow(), 0)));
            dispose();
        }
        if(evt.getKeyCode() == evt.VK_ESCAPE)
        {
            jText.setText(jText.getText());
            dispose();
        }
    }//GEN-LAST:event_jTDetallesCuentaKeyPressed

    private void jTFDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDescripcionFocusGained
        jTFDescripcion.selectAll();
    }//GEN-LAST:event_jTFDescripcionFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgConsultasCuentasMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgConsultasCuentasMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgConsultasCuentasMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgConsultasCuentasMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgConsultasCuentasMonedas dialog = new DlgConsultasCuentasMonedas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTDetallesCuenta;
    public static javax.swing.JTextField jTFDescripcion;
    // End of variables declaration//GEN-END:variables
}
