/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views.busca;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import ModRegistros.Articulos;
import utiles.DBManager;
import utiles.InfoErrores;
import utiles.MaxLength;
import utiles.TGridTableModel;

/**
 *
 * @author Andres
 */
public class DlgConsultasSubgrupo extends javax.swing.JDialog {

    DefaultTableModel dtm = new DefaultTableModel(null, new String[]{"Código", "Descripción", "Cód Grupo", "Margen"});
    private ResultSet rs = null;
    private static JTextField jText;
    String modulo;
    
    /**
     * Creates new form DlgConsultas
     */
    public DlgConsultasSubgrupo(java.awt.Frame parent, boolean modal, String modulo) {
        super(parent, modal);
        initComponents();
        
        this.modulo = modulo;
        configTabla();
        tfDescripcionBusqueda.setText("%");
        
        Dimension screenSize;
        screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dialogSize = getSize();
        if(dialogSize.height > screenSize.height)
        {
            dialogSize.height = screenSize.height;
        }
        if(dialogSize.width > screenSize.width)
        {
            dialogSize.width = screenSize.width;
        }
        setLocation((screenSize.width - dialogSize.width) / 2,(screenSize.height - dialogSize.height) / 2);
        
        tfDescripcionBusqueda.setDocument(new MaxLength(40, "UPPER", "ALFA"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfDescripcionBusqueda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ATOMSystems|Main - Búsqueda de SubGrupos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Ingrese información a buscar:");

        tfDescripcionBusqueda.setText("%");
        tfDescripcionBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfDescripcionBusquedaKeyPressed(evt);
            }
        });

        tbBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbBuscarKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbBuscar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDescripcionBusqueda)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDescripcionBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(727, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfDescripcionBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDescripcionBusquedaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            try{
                limpiarGrillas();
                String sql = "";
                if(!tfDescripcionBusqueda.getText().trim().equals("")){
                    if(modulo.equals("ARTICULOS")){
                        sql = "SELECT cod_subgrupo, descripcion, cod_grupo, margen_base_vta FROM subgrupo WHERE "
                            + "descripcion LIKE '%" + tfDescripcionBusqueda.getText().trim() + "%' AND cod_grupo = " + Articulos.jTFCodGrupo.getText().trim();
                    }else{
                        sql = "SELECT cod_subgrupo, descripcion, cod_grupo, margen_base_vta FROM subgrupo WHERE "
                            + "descripcion LIKE '%" + tfDescripcionBusqueda.getText().trim() + "%' AND cod_grupo = " + BuscaArticuloFiltro.jTFCodGrupo.getText().trim();
                    }                    
                    rs = DBManager.ejecutarDSL(sql);
                    System.out.println("SQL BUSQUEDA: " + sql);
                    if(rs != null){
                        while(rs.next()){
                            Object[] row = new Object[4];
                            row[0] = rs.getInt("cod_subgrupo");
                            row[1] = rs.getString("descripcion");
                            row[2] = rs.getInt("cod_grupo");
                            row[3] = rs.getDouble("margen_base_vta");
                            dtm.addRow(row);
                        }
                        tbBuscar.updateUI();
                        tbBuscar.grabFocus();
                    }else{
                        JOptionPane.showMessageDialog(this, "ATENCION: Ningún registro encontrado!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "ATENCION: por favor ingrese una descripción!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                }
            }catch(Exception ex){
                ex.printStackTrace();
                InfoErrores.errores(ex);
            }
        }
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            jText.setText("0");
            dispose();
        }
    }//GEN-LAST:event_tfDescripcionBusquedaKeyPressed

    private void tbBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbBuscarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            jText.setText(String.valueOf(tbBuscar.getValueAt(tbBuscar.getSelectedRow(), 0)));
            dispose();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE)
        {
            jText.setText(jText.getText());
            dispose();
        }
    }//GEN-LAST:event_tbBuscarKeyPressed

    private static void setDataSet(ResultSet resultSet, Vector columnName)
    {
        try
        {
            if(resultSet != null && columnName != null)
            {
                Vector lineas = new Vector();
                while(resultSet.next())
                {
                    Vector nuevaLinea = new Vector();
                    for(int cont = 1; cont <= resultSet.getMetaData().getColumnCount(); cont++)
                    {
                        nuevaLinea.addElement(resultSet.getObject(cont));
                    }
                    lineas.addElement(nuevaLinea);
                }
                tbBuscar.setModel(new TGridTableModel(lineas, columnName));
            }
        }catch(Exception ex)
        {
            ex.printStackTrace();
            InfoErrores.errores(ex);
        }
    }
    
    private void limpiarGrillas()
    {
        for (int i = 0; i < tbBuscar.getRowCount(); i++) {
                dtm.removeRow(i);
                i--;
            }
    }
    
    public static void setText(JTextField jTf)
    {
        jText = jTf;
    }
    
    private void configTabla()
    {
        tbBuscar.setModel(dtm);
        
        tbBuscar.getColumnModel().getColumn(0).setPreferredWidth(5);
        tbBuscar.getColumnModel().getColumn(1).setPreferredWidth(130);
        tbBuscar.getColumnModel().getColumn(2).setPreferredWidth(200);
        tbBuscar.getColumnModel().getColumn(3).setPreferredWidth(30);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgConsultasSubgrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgConsultasSubgrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgConsultasSubgrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgConsultasSubgrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgConsultasSubgrupo dialog = new DlgConsultasSubgrupo(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static final javax.swing.JTable tbBuscar = new javax.swing.JTable();
    public static javax.swing.JTextField tfDescripcionBusqueda;
    // End of variables declaration//GEN-END:variables
}
