/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModRRHH;

import beans.SeccionBean;
import controls.BarrioCtrl;
import controls.CentroCostoCtrl;
import controls.EmpresaCtrl;
import controls.SeccionCtrl;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import principal.FormMain;
import utiles.Focus;
import utiles.InfoErrores;
import utiles.MaxLength;
import utiles.Utiles;
import views.busca.DlgConsultas;

/**
 *
 * @author Andres
 */
public class Seccion extends javax.swing.JDialog {

    /**
     * Creates new form Marcas
     */
    
    boolean esNuevo = false;
    
    public Seccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setConfigCampos();
        cargaSeccion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jBNuevo = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jBBuscarCodigo = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFCodCentroCosto = new javax.swing.JTextField();
        jTFDescCentroCosto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCbActivo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jTFCargaHoraria = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTFCodEmpresa = new javax.swing.JTextField();
        jLNombreEmpresa = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(204, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mantenimiento de Proveedores");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ATOMSystems|Main - Secciones");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("MANTENIMIENTO DE SECCIONES ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Opciones"));

        jBNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/nuevo24.png"))); // NOI18N
        jBNuevo.setText("Nuevo");
        jBNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoActionPerformed(evt);
            }
        });

        jBModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/modificar24.png"))); // NOI18N
        jBModificar.setText("Modificar");
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });

        jBGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/guardar24.png"))); // NOI18N
        jBGuardar.setText("Grabar");
        jBGuardar.setEnabled(false);
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        jBGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBGuardarKeyPressed(evt);
            }
        });

        jBBuscarCodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/buscar24.png"))); // NOI18N
        jBBuscarCodigo.setText("Buscar");
        jBBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarCodigoActionPerformed(evt);
            }
        });

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cancelar24.png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.setEnabled(false);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jBCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBCancelarKeyPressed(evt);
            }
        });

        jBSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/salir24.png"))); // NOI18N
        jBSalir.setText("Salir");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBBuscarCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBBuscarCodigo, jBCancelar, jBGuardar, jBModificar, jBNuevo, jBSalir});

        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNuevo)
                    .addComponent(jBModificar)
                    .addComponent(jBGuardar)
                    .addComponent(jBBuscarCodigo)
                    .addComponent(jBCancelar)
                    .addComponent(jBSalir))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBBuscarCodigo, jBCancelar, jBGuardar, jBModificar, jBNuevo, jBSalir});

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Código:");

        jTFCodigo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFCodigo.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Descripción:");

        jTFDescripcion.setEnabled(false);
        jTFDescripcion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFDescripcionFocusGained(evt);
            }
        });
        jTFDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFDescripcionKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Centro de costo:");

        jTFCodCentroCosto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFCodCentroCosto.setEnabled(false);
        jTFCodCentroCosto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFCodCentroCostoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTFCodCentroCostoFocusLost(evt);
            }
        });
        jTFCodCentroCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCodCentroCostoKeyPressed(evt);
            }
        });

        jTFDescCentroCosto.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Activo:");

        jCbActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "N" }));
        jCbActivo.setEnabled(false);
        jCbActivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCbActivoKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Carga horaria:");

        jTFCargaHoraria.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFCargaHoraria.setEnabled(false);
        jTFCargaHoraria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFCargaHorariaFocusGained(evt);
            }
        });
        jTFCargaHoraria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTFCargaHorariaKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Empresa:");

        jTFCodEmpresa.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTFCodEmpresa.setEnabled(false);

        jLNombreEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLNombreEmpresa.setText("***");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCodEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLNombreEmpresa))
                    .addComponent(jTFDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTFCargaHoraria, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFCodCentroCosto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFDescCentroCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTFCodEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNombreEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFCodCentroCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFDescCentroCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCbActivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTFCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(716, 383));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNuevoActionPerformed
        esNuevo = true;
        setComponentesNuevo();
        llenarCamposRegistro();
    }//GEN-LAST:event_jBNuevoActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        esNuevo = false;
        setComponentesModificar();
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        if (verificaCampos()) {
            grabarSeccion();
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarCodigoActionPerformed
       
        DlgConsultas seccion = new DlgConsultas(new JFrame(), true);
        seccion.pack();
        seccion.setTitle("Consulta de Secciones");
        seccion.dConsultas("seccion", "des_seccion", "cod_seccion", "des_seccion", "fec_vigencia", null, "Codigo", "Descripción", "Registro", null);
        seccion.setText(jTFCodigo);
        seccion.setVisible(true);
        getSeccion(Integer.parseInt(jTFCodigo.getText()));
        jBModificar.grabFocus();
    }//GEN-LAST:event_jBBuscarCodigoActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        setComponentesCancelar();
        cargaSeccion();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBCancelarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelarKeyPressed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jTFDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDescripcionKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTFCodCentroCosto.requestFocus();
        }
    }//GEN-LAST:event_jTFDescripcionKeyPressed

    private void jTFCodCentroCostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCodCentroCostoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jCbActivo.requestFocus();
        }
        
        if (evt.getKeyCode() == KeyEvent.VK_F1) {
            try {
                DlgConsultas grupo = new DlgConsultas(new JFrame(), true);
                grupo.pack();
                grupo.setTitle("Consulta de Ciudad");
                grupo.dConsultas("ciudad", "nombre", "cod_ciudad", "nombre", "fec_vigencia", null, "Codigo", "Nombre", "Registro", null);
                grupo.setText(jTFCodCentroCosto);
                grupo.setVisible(true);
            } catch (Exception ex) {
                ex.printStackTrace();
                InfoErrores.errores(ex);
                JOptionPane.showMessageDialog(this, "No se pudo crear el Formulario de Consulta!", "ATENCION", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jTFCodCentroCostoKeyPressed

    private void jBGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBGuardarKeyPressed
        jBGuardar.doClick();
    }//GEN-LAST:event_jBGuardarKeyPressed

    private void jTFCodCentroCostoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodCentroCostoFocusLost
        jTFDescCentroCosto.setText(getDescCentroCosto(jTFCodCentroCosto.getText().trim()));
    }//GEN-LAST:event_jTFCodCentroCostoFocusLost

    private void jTFDescripcionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDescripcionFocusGained
        jTFDescripcion.selectAll();
    }//GEN-LAST:event_jTFDescripcionFocusGained

    private void jTFCodCentroCostoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCodCentroCostoFocusGained
        jTFCodCentroCosto.selectAll();
    }//GEN-LAST:event_jTFCodCentroCostoFocusGained

    private void jCbActivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCbActivoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jTFCargaHoraria.grabFocus();
        }
    }//GEN-LAST:event_jCbActivoKeyPressed

    private void jTFCargaHorariaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCargaHorariaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            jBGuardar.grabFocus();
        }
    }//GEN-LAST:event_jTFCargaHorariaKeyPressed

    private void jTFCargaHorariaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFCargaHorariaFocusGained
        jTFCargaHoraria.selectAll();
    }//GEN-LAST:event_jTFCargaHorariaFocusGained

    private void grabarSeccion(){
        try{
            String fecVigencia = "";
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy hh:mm:ss a");
                java.util.Date d = new java.util.Date();
                fecVigencia = sdf.format(d);
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error Formateando Fecha...");
            }
            
            SeccionBean bBean = new SeccionBean();
            bBean.setActivo(jCbActivo.getSelectedItem().toString());
            bBean.setCargaHoraria(Integer.parseInt(jTFCargaHoraria.getText()));
            bBean.setCodCentroCosto(Integer.parseInt(jTFCodCentroCosto.getText()));
            bBean.setCodEmpresa(Integer.parseInt(jTFCodEmpresa.getText()));
            bBean.setCodSeccion(Integer.parseInt(jTFCodigo.getText()));
            bBean.setDescripcion(jTFDescripcion.getText());
            bBean.setCodUsuario(FormMain.codUsuario);
            bBean.setFecVigencia(fecVigencia);
            
            SeccionCtrl bCtrl = new SeccionCtrl();
            if(esNuevo){
                if(bCtrl.catastrarSeccion(bBean)){
                    JOptionPane.showMessageDialog(this, "Sección registrado con éxito !!!", "OK", JOptionPane.INFORMATION_MESSAGE);
                    setComponentesGrabado();
                    cargaSeccion();
                }else{
                    JOptionPane.showMessageDialog(this, "Error al Registrar Sección !!!", "Error", JOptionPane.INFORMATION_MESSAGE);
                }
            }else{ // modificacion
                if(bCtrl.alteraSeccion(bBean)){
                    JOptionPane.showMessageDialog(this, "Sección Modificado con Suceso !!!", "OK", JOptionPane.INFORMATION_MESSAGE);
                    setComponentesGrabado();
                }else{
                    JOptionPane.showMessageDialog(this, "ATENCION: Error al Modificar Sección !!!", "Error", JOptionPane.WARNING_MESSAGE);
                }
            }
        }catch(Exception ex){
            ex.printStackTrace();
            InfoErrores.errores(ex);
            JOptionPane.showMessageDialog(this, "ATENCION: Error al grabar Sección !!!", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void setComponentesGrabado() {

        jTFDescripcion.setEnabled(false);
        jTFCodCentroCosto.setEnabled(false);
        jCbActivo.setEnabled(false);
        jTFCargaHoraria.setEnabled(false);

        jBNuevo.setEnabled(true);
        jBModificar.setEnabled(true);
        jBBuscarCodigo.setEnabled(true);
        jBSalir.setEnabled(true);
        jBCancelar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBNuevo.grabFocus();
    }
    
    private void cargaSeccion() {
        SeccionCtrl bCtrl = new SeccionCtrl();
        int max = bCtrl.buscaMaxCodSeccion();
        if (max > 0) {
            getSeccion(max);
        } else {
            jBModificar.setEnabled(false);
        }
    }
    
    private void getSeccion(int codigo) {
        SeccionCtrl bCtrl = new SeccionCtrl();
        SeccionBean bBean = bCtrl.buscaSeccionCodigo(codigo);
        if (bBean != null) {
            jTFCodigo.setText(String.valueOf(bBean.getCodSeccion()));
            jTFDescripcion.setText(bBean.getDescripcion());
            jTFCodCentroCosto.setText(String.valueOf(bBean.getCodCentroCosto()));
            jTFDescCentroCosto.setText(getDescCentroCosto(jTFCodCentroCosto.getText().trim()));
            jTFCodEmpresa.setText(String.valueOf(bBean.getCodEmpresa()));
            jLNombreEmpresa.setText(getDescripcionEmpresa(jTFCodEmpresa.getText()));
            jCbActivo.setSelectedItem(bBean.getActivo());
            jTFCargaHoraria.setText(String.valueOf(bBean.getCargaHoraria()));
        }
    }
    
    private String getDescCentroCosto(String codigo) {
        String result = "";
        if (Utiles.isIntegerValid(codigo)) {
            CentroCostoCtrl ctrl = new CentroCostoCtrl();
            result = ctrl.getNombreCentroCosto(Integer.valueOf(codigo));
            ctrl = null;
        }
        return result;
    }
    
    private String getDescripcionEmpresa(String codigo){
        String result = "";
        if(Utiles.isIntegerValid(codigo)){
            EmpresaCtrl ctrl = new EmpresaCtrl();
            result = ctrl.getDescripcionEmpresa(Integer.parseInt(codigo));
            ctrl = null;
        }
        return result;
    }
    
    private boolean verificaCampos(){
        if(jTFDescripcion.getText().trim().equals("")){
            JOptionPane.showMessageDialog(this, "ATENCION: Complete el campo DESCRIPCION !!!", "Error", JOptionPane.WARNING_MESSAGE);
            jTFDescripcion.requestFocus();
            return false;
        }
        return true;
    }
    
    private void setComponentesCancelar() {
        jTFDescripcion.setEnabled(false);
        jTFCodCentroCosto.setEnabled(false);
        jTFCargaHoraria.setEnabled(false);
        jCbActivo.setEnabled(false);
        jBNuevo.grabFocus();

        jBBuscarCodigo.setEnabled(true);
        jBCancelar.setEnabled(false);
        jBGuardar.setEnabled(false);
        jBModificar.setEnabled(true);
        jBNuevo.setEnabled(true);
        jBSalir.setEnabled(true);
    }
    
    private void setComponentesNuevo() {
        jTFDescripcion.setEnabled(true);
        jTFCodCentroCosto.setEnabled(true);
        jTFCargaHoraria.setEnabled(true);
        jCbActivo.setEnabled(true);
        
        jTFDescripcion.grabFocus();

        jBBuscarCodigo.setEnabled(false);
        jBCancelar.setEnabled(true);
        jBGuardar.setEnabled(true);
        jBModificar.setEnabled(false);
        jBNuevo.setEnabled(false);
        jBSalir.setEnabled(true);
    }
    
    private void setConfigCampos() {

        jTFDescripcion.setDocument(new MaxLength(40, "UPPER", "ALFA"));
        jTFCodCentroCosto.setDocument(new MaxLength(5, "", "ENTERO"));
        jTFCargaHoraria.setDocument(new MaxLength(3, "", "ENTERO"));
        
        jTFDescripcion.addFocusListener(new Focus());
        jTFCodCentroCosto.addFocusListener(new Focus());
        jCbActivo.addFocusListener(new Focus());
        jTFCargaHoraria.addFocusListener(new Focus());
    }
    
    private void llenarCamposRegistro() {

        jTFCodigo.setText(getCodigoSeccion());
        jTFDescripcion.setText("");
        jTFCodCentroCosto.setText("1");
        jTFCargaHoraria.setText("1");
        jTFCodEmpresa.setText(Utiles.getCodEmpresaDefault());
        jLNombreEmpresa.setText(getDescripcionEmpresa(jTFCodEmpresa.getText()));
    }
    
    private String getCodigoSeccion() {
        BarrioCtrl bCtrl = new BarrioCtrl();
        int result = bCtrl.buscaMaxCodBarrio();
        result = result + 1;
        return String.valueOf(result);
    }
    
    private void setComponentesModificar(){
        jTFDescripcion.setEnabled(true);
        jTFCodCentroCosto.setEnabled(true);
        jCbActivo.setEnabled(true);
        jTFCargaHoraria.setEnabled(true);
        jTFDescripcion.grabFocus();
        
        jBNuevo.setEnabled(false);
        jBModificar.setEnabled(false);
        jBBuscarCodigo.setEnabled(false);
        jBSalir.setEnabled(false);
        jBGuardar.setEnabled(true);
        jBCancelar.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Seccion dialog = new Seccion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarCodigo;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JButton jBNuevo;
    private javax.swing.JButton jBSalir;
    private javax.swing.JComboBox<String> jCbActivo;
    private javax.swing.JLabel jLNombreEmpresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTFCargaHoraria;
    private javax.swing.JTextField jTFCodCentroCosto;
    private javax.swing.JTextField jTFCodEmpresa;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFDescCentroCosto;
    private javax.swing.JTextField jTFDescripcion;
    // End of variables declaration//GEN-END:variables
}
